// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package storedb

import (
	"context"
	"database/sql"
)

const contactSeenInDM = `-- name: ContactSeenInDM :one
SELECT EXISTS (
	SELECT 1 FROM chats
	WHERE session_id = ? AND type = 'dm'
		AND (chat_jid = ? OR (? <> '' AND chat_jid = ?))
)
`

type ContactSeenInDMParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Lid       string `db:"lid" json:"lid"`
	PhoneJid  string `db:"phone_jid" json:"phone_jid"`
}

func (q *Queries) ContactSeenInDM(ctx context.Context, arg ContactSeenInDMParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, contactSeenInDM,
		arg.SessionID,
		arg.Lid,
		arg.PhoneJid,
		arg.PhoneJid,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listContactsAnywhere = `-- name: ListContactsAnywhere :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name,
	EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid))) AS in_dm,
	EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid) AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND (EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid)))
		OR EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid))
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsAnywhereParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	AfterID   uint64 `db:"after_id" json:"after_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

type ListContactsAnywhereRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         bool           `db:"in_dm" json:"in_dm"`
	InGroup      bool           `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsAnywhere(ctx context.Context, arg ListContactsAnywhereParams) ([]ListContactsAnywhereRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsAnywhere,
		arg.SessionID,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.SessionID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsAnywhereRow{}
	for rows.Next() {
		var i ListContactsAnywhereRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsAnywhereSearch = `-- name: ListContactsAnywhereSearch :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name,
	EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid))) AS in_dm,
	EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid) AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND (EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid)))
		OR EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid))
	AND i.name LIKE ?
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsAnywhereSearchParams struct {
	SessionID   string         `db:"session_id" json:"session_id"`
	AfterID     uint64         `db:"after_id" json:"after_id"`
	NamePattern sql.NullString `db:"name_pattern" json:"name_pattern"`
	Limit       int32          `db:"limit" json:"limit"`
}

type ListContactsAnywhereSearchRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         bool           `db:"in_dm" json:"in_dm"`
	InGroup      bool           `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsAnywhereSearch(ctx context.Context, arg ListContactsAnywhereSearchParams) ([]ListContactsAnywhereSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsAnywhereSearch,
		arg.SessionID,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.SessionID,
		arg.NamePattern,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsAnywhereSearchRow{}
	for rows.Next() {
		var i ListContactsAnywhereSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByGroup = `-- name: ListContactsByGroup :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name,
	EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid))) AS in_dm,
	TRUE AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid AND gm.group_jid = ?)
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsByGroupParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	AfterID   uint64 `db:"after_id" json:"after_id"`
	GroupJid  string `db:"group_jid" json:"group_jid"`
	Limit     int32  `db:"limit" json:"limit"`
}

type ListContactsByGroupRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         bool           `db:"in_dm" json:"in_dm"`
	InGroup      int32          `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsByGroup(ctx context.Context, arg ListContactsByGroupParams) ([]ListContactsByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsByGroup,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.GroupJid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsByGroupRow{}
	for rows.Next() {
		var i ListContactsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByGroupSearch = `-- name: ListContactsByGroupSearch :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name,
	EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid))) AS in_dm,
	TRUE AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid AND gm.group_jid = ?)
	AND i.name LIKE ?
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsByGroupSearchParams struct {
	SessionID   string         `db:"session_id" json:"session_id"`
	AfterID     uint64         `db:"after_id" json:"after_id"`
	GroupJid    string         `db:"group_jid" json:"group_jid"`
	NamePattern sql.NullString `db:"name_pattern" json:"name_pattern"`
	Limit       int32          `db:"limit" json:"limit"`
}

type ListContactsByGroupSearchRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         bool           `db:"in_dm" json:"in_dm"`
	InGroup      int32          `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsByGroupSearch(ctx context.Context, arg ListContactsByGroupSearchParams) ([]ListContactsByGroupSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsByGroupSearch,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.GroupJid,
		arg.NamePattern,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsByGroupSearchRow{}
	for rows.Next() {
		var i ListContactsByGroupSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsDM = `-- name: ListContactsDM :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name, TRUE AS in_dm,
	EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid) AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid)))
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsDMParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	AfterID   uint64 `db:"after_id" json:"after_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

type ListContactsDMRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         int32          `db:"in_dm" json:"in_dm"`
	InGroup      bool           `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsDM(ctx context.Context, arg ListContactsDMParams) ([]ListContactsDMRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsDM,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsDMRow{}
	for rows.Next() {
		var i ListContactsDMRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsDMSearch = `-- name: ListContactsDMSearch :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name, TRUE AS in_dm,
	EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid) AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid)))
	AND i.name LIKE ?
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsDMSearchParams struct {
	SessionID   string         `db:"session_id" json:"session_id"`
	AfterID     uint64         `db:"after_id" json:"after_id"`
	NamePattern sql.NullString `db:"name_pattern" json:"name_pattern"`
	Limit       int32          `db:"limit" json:"limit"`
}

type ListContactsDMSearchRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         int32          `db:"in_dm" json:"in_dm"`
	InGroup      bool           `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsDMSearch(ctx context.Context, arg ListContactsDMSearchParams) ([]ListContactsDMSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsDMSearch,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.NamePattern,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsDMSearchRow{}
	for rows.Next() {
		var i ListContactsDMSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsGroup = `-- name: ListContactsGroup :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name,
	EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid))) AS in_dm,
	TRUE AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid)
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsGroupParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	AfterID   uint64 `db:"after_id" json:"after_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

type ListContactsGroupRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         bool           `db:"in_dm" json:"in_dm"`
	InGroup      int32          `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsGroup(ctx context.Context, arg ListContactsGroupParams) ([]ListContactsGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsGroup,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsGroupRow{}
	for rows.Next() {
		var i ListContactsGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsGroupSearch = `-- name: ListContactsGroupSearch :many
SELECT i.id, i.lid, i.phone_number, i.name, i.business_name,
	EXISTS (SELECT 1 FROM chats ch WHERE ch.session_id = ? AND ch.type = 'dm' AND (ch.chat_jid = i.lid OR (i.phone_jid IS NOT NULL AND ch.chat_jid = i.phone_jid))) AS in_dm,
	TRUE AS in_group
FROM whatsapp_identities i
WHERE i.id > ?
	AND EXISTS (SELECT 1 FROM whatsapp_group_members gm WHERE gm.session_id = ? AND gm.lid = i.lid)
	AND i.name LIKE ?
ORDER BY i.id ASC
LIMIT ?
`

type ListContactsGroupSearchParams struct {
	SessionID   string         `db:"session_id" json:"session_id"`
	AfterID     uint64         `db:"after_id" json:"after_id"`
	NamePattern sql.NullString `db:"name_pattern" json:"name_pattern"`
	Limit       int32          `db:"limit" json:"limit"`
}

type ListContactsGroupSearchRow struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	InDm         bool           `db:"in_dm" json:"in_dm"`
	InGroup      int32          `db:"in_group" json:"in_group"`
}

func (q *Queries) ListContactsGroupSearch(ctx context.Context, arg ListContactsGroupSearchParams) ([]ListContactsGroupSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactsGroupSearch,
		arg.SessionID,
		arg.AfterID,
		arg.SessionID,
		arg.NamePattern,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsGroupSearchRow{}
	for rows.Next() {
		var i ListContactsGroupSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Lid,
			&i.PhoneNumber,
			&i.Name,
			&i.BusinessName,
			&i.InDm,
			&i.InGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
