// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package storedb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const appendEventLog = `-- name: AppendEventLog :execresult
INSERT INTO event_log (event_id, organization_id, session_id, type, payload, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type AppendEventLogParams struct {
	EventID        string          `db:"event_id" json:"event_id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      string          `db:"session_id" json:"session_id"`
	Type           string          `db:"type" json:"type"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
}

func (q *Queries) AppendEventLog(ctx context.Context, arg AppendEventLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, appendEventLog,
		arg.EventID,
		arg.OrganizationID,
		arg.SessionID,
		arg.Type,
		arg.Payload,
		arg.CreatedAt,
	)
}

const getEventLogByEventID = `-- name: GetEventLogByEventID :one
SELECT id, event_id, organization_id, session_id, type, payload, created_at
FROM event_log
WHERE event_id = ?
`

type GetEventLogByEventIDParams struct {
	EventID string `db:"event_id" json:"event_id"`
}

func (q *Queries) GetEventLogByEventID(ctx context.Context, arg GetEventLogByEventIDParams) (EventLog, error) {
	row := q.db.QueryRowContext(ctx, getEventLogByEventID, arg.EventID)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventLogSinceForOrg = `-- name: ListEventLogSinceForOrg :many
SELECT id, event_id, organization_id, session_id, type, payload, created_at
FROM event_log
WHERE organization_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListEventLogSinceForOrgParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	ID             uint64 `db:"id" json:"id"`
	Limit          int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListEventLogSinceForOrg(ctx context.Context, arg ListEventLogSinceForOrgParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listEventLogSinceForOrg, arg.OrganizationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLogSinceForSession = `-- name: ListEventLogSinceForSession :many
SELECT id, event_id, organization_id, session_id, type, payload, created_at
FROM event_log
WHERE organization_id = ? AND session_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListEventLogSinceForSessionParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
	SessionID      string `db:"session_id" json:"session_id"`
	ID             uint64 `db:"id" json:"id"`
	Limit          int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListEventLogSinceForSession(ctx context.Context, arg ListEventLogSinceForSessionParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listEventLogSinceForSession,
		arg.OrganizationID,
		arg.SessionID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
