// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway.sql

package storedb

import (
	"context"
	"database/sql"
)

const gatewayHeartbeat = `-- name: GatewayHeartbeat :exec
UPDATE gateways
SET last_seen_at = ?, session_count = ?, updated_at = ?
WHERE id = ?
`

type GatewayHeartbeatParams struct {
	LastSeenAt   sql.NullInt64 `db:"last_seen_at" json:"last_seen_at"`
	SessionCount uint32        `db:"session_count" json:"session_count"`
	UpdatedAt    int64         `db:"updated_at" json:"updated_at"`
	ID           string        `db:"id" json:"id"`
}

func (q *Queries) GatewayHeartbeat(ctx context.Context, arg GatewayHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, gatewayHeartbeat,
		arg.LastSeenAt,
		arg.SessionCount,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getGateway = `-- name: GetGateway :one
SELECT id, label, status, session_count, capacity, base_url, last_seen_at, created_at, updated_at
FROM gateways
WHERE id = ?
`

type GetGatewayParams struct {
	ID string `db:"id" json:"id"`
}

type GetGatewayRow struct {
	ID           string         `db:"id" json:"id"`
	Label        sql.NullString `db:"label" json:"label"`
	Status       string         `db:"status" json:"status"`
	SessionCount uint32         `db:"session_count" json:"session_count"`
	Capacity     sql.NullInt32  `db:"capacity" json:"capacity"`
	BaseUrl      sql.NullString `db:"base_url" json:"base_url"`
	LastSeenAt   sql.NullInt64  `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt    int64          `db:"created_at" json:"created_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetGateway(ctx context.Context, arg GetGatewayParams) (GetGatewayRow, error) {
	row := q.db.QueryRowContext(ctx, getGateway, arg.ID)
	var i GetGatewayRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.SessionCount,
		&i.Capacity,
		&i.BaseUrl,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGateways = `-- name: ListActiveGateways :many
SELECT id, label, status, session_count, capacity, base_url, last_seen_at, created_at, updated_at
FROM gateways
WHERE status = ?
ORDER BY session_count ASC, id ASC
`

type ListActiveGatewaysParams struct {
	Status string `db:"status" json:"status"`
}

type ListActiveGatewaysRow struct {
	ID           string         `db:"id" json:"id"`
	Label        sql.NullString `db:"label" json:"label"`
	Status       string         `db:"status" json:"status"`
	SessionCount uint32         `db:"session_count" json:"session_count"`
	Capacity     sql.NullInt32  `db:"capacity" json:"capacity"`
	BaseUrl      sql.NullString `db:"base_url" json:"base_url"`
	LastSeenAt   sql.NullInt64  `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt    int64          `db:"created_at" json:"created_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListActiveGateways(ctx context.Context, arg ListActiveGatewaysParams) ([]ListActiveGatewaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGateways, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGatewaysRow{}
	for rows.Next() {
		var i ListActiveGatewaysRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.SessionCount,
			&i.Capacity,
			&i.BaseUrl,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickGatewayForPlacement = `-- name: PickGatewayForPlacement :one
SELECT id, label, status, session_count, capacity, base_url, last_seen_at, created_at, updated_at
FROM gateways
WHERE status = ? AND (capacity IS NULL OR session_count < capacity)
ORDER BY session_count ASC, last_seen_at DESC, id ASC
LIMIT 1
`

type PickGatewayForPlacementParams struct {
	Status string `db:"status" json:"status"`
}

type PickGatewayForPlacementRow struct {
	ID           string         `db:"id" json:"id"`
	Label        sql.NullString `db:"label" json:"label"`
	Status       string         `db:"status" json:"status"`
	SessionCount uint32         `db:"session_count" json:"session_count"`
	Capacity     sql.NullInt32  `db:"capacity" json:"capacity"`
	BaseUrl      sql.NullString `db:"base_url" json:"base_url"`
	LastSeenAt   sql.NullInt64  `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt    int64          `db:"created_at" json:"created_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) PickGatewayForPlacement(ctx context.Context, arg PickGatewayForPlacementParams) (PickGatewayForPlacementRow, error) {
	row := q.db.QueryRowContext(ctx, pickGatewayForPlacement, arg.Status)
	var i PickGatewayForPlacementRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.SessionCount,
		&i.Capacity,
		&i.BaseUrl,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGatewayStatus = `-- name: SetGatewayStatus :exec
UPDATE gateways
SET status = ?, updated_at = ?
WHERE id = ?
`

type SetGatewayStatusParams struct {
	Status    string `db:"status" json:"status"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) SetGatewayStatus(ctx context.Context, arg SetGatewayStatusParams) error {
	_, err := q.db.ExecContext(ctx, setGatewayStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertGateway = `-- name: UpsertGateway :exec
INSERT INTO gateways (id, label, status, session_count, capacity, base_url, last_seen_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE label=VALUES(label), status=VALUES(status),
	capacity=VALUES(capacity), base_url=VALUES(base_url),
	last_seen_at=VALUES(last_seen_at), updated_at=VALUES(updated_at)
`

type UpsertGatewayParams struct {
	ID           string         `db:"id" json:"id"`
	Label        sql.NullString `db:"label" json:"label"`
	Status       string         `db:"status" json:"status"`
	SessionCount uint32         `db:"session_count" json:"session_count"`
	Capacity     sql.NullInt32  `db:"capacity" json:"capacity"`
	BaseUrl      sql.NullString `db:"base_url" json:"base_url"`
	LastSeenAt   sql.NullInt64  `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt    int64          `db:"created_at" json:"created_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertGateway(ctx context.Context, arg UpsertGatewayParams) error {
	_, err := q.db.ExecContext(ctx, upsertGateway,
		arg.ID,
		arg.Label,
		arg.Status,
		arg.SessionCount,
		arg.Capacity,
		arg.BaseUrl,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
