// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_control.sql

package storedb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
INSERT INTO audit_events
(id, organization_id, actor_type, actor_id, action, resource_type, resource_id, outcome, request_id, source_ip, metadata, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendAuditEventParams struct {
	ID             string               `db:"id" json:"id"`
	OrganizationID sql.NullString       `db:"organization_id" json:"organization_id"`
	ActorType      AuditEventsActorType `db:"actor_type" json:"actor_type"`
	ActorID        sql.NullString       `db:"actor_id" json:"actor_id"`
	Action         string               `db:"action" json:"action"`
	ResourceType   string               `db:"resource_type" json:"resource_type"`
	ResourceID     sql.NullString       `db:"resource_id" json:"resource_id"`
	Outcome        AuditEventsOutcome   `db:"outcome" json:"outcome"`
	RequestID      sql.NullString       `db:"request_id" json:"request_id"`
	SourceIp       sql.NullString       `db:"source_ip" json:"source_ip"`
	Metadata       json.RawMessage      `db:"metadata" json:"metadata"`
	CreatedAt      int64                `db:"created_at" json:"created_at"`
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditEvent,
		arg.ID,
		arg.OrganizationID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Outcome,
		arg.RequestID,
		arg.SourceIp,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const beginGatewayEnrollment = `-- name: BeginGatewayEnrollment :execrows
UPDATE gateway_enrollment_tokens
SET status='redeeming', redemption_nonce=?, csr_sha256=?, redeeming_at=?, lease_expires_at=?,
    attempt_count=attempt_count+1, updated_at=?
WHERE id=? AND expires_at>? AND attempt_count<max_attempts
  AND (status='active' OR (status='redeeming' AND lease_expires_at<=? AND csr_sha256=?))
`

type BeginGatewayEnrollmentParams struct {
	RedemptionNonce  sql.NullString `db:"redemption_nonce" json:"redemption_nonce"`
	CsrSha256        sql.NullString `db:"csr_sha256" json:"csr_sha256"`
	RedeemingAt      sql.NullInt64  `db:"redeeming_at" json:"redeeming_at"`
	LeaseExpiresAt   sql.NullInt64  `db:"lease_expires_at" json:"lease_expires_at"`
	UpdatedAt        int64          `db:"updated_at" json:"updated_at"`
	ID               string         `db:"id" json:"id"`
	ExpiresAt        int64          `db:"expires_at" json:"expires_at"`
	LeaseExpiresAt_2 sql.NullInt64  `db:"lease_expires_at_2" json:"lease_expires_at_2"`
	CsrSha256_2      sql.NullString `db:"csr_sha256_2" json:"csr_sha256_2"`
}

func (q *Queries) BeginGatewayEnrollment(ctx context.Context, arg BeginGatewayEnrollmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, beginGatewayEnrollment,
		arg.RedemptionNonce,
		arg.CsrSha256,
		arg.RedeemingAt,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpiresAt,
		arg.LeaseExpiresAt_2,
		arg.CsrSha256_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finalizeGatewayEnrollment = `-- name: FinalizeGatewayEnrollment :execrows
UPDATE gateway_enrollment_tokens
SET status='consumed', consumed_at=?, redemption_nonce=NULL, csr_sha256=NULL,
    redeeming_at=NULL, lease_expires_at=NULL, updated_at=?
WHERE id=? AND status='redeeming' AND redemption_nonce=? AND csr_sha256=? AND lease_expires_at>?
`

type FinalizeGatewayEnrollmentParams struct {
	ConsumedAt      sql.NullInt64  `db:"consumed_at" json:"consumed_at"`
	UpdatedAt       int64          `db:"updated_at" json:"updated_at"`
	ID              string         `db:"id" json:"id"`
	RedemptionNonce sql.NullString `db:"redemption_nonce" json:"redemption_nonce"`
	CsrSha256       sql.NullString `db:"csr_sha256" json:"csr_sha256"`
	LeaseExpiresAt  sql.NullInt64  `db:"lease_expires_at" json:"lease_expires_at"`
}

func (q *Queries) FinalizeGatewayEnrollment(ctx context.Context, arg FinalizeGatewayEnrollmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeGatewayEnrollment,
		arg.ConsumedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.RedemptionNonce,
		arg.CsrSha256,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGatewayEnrollmentTokenForUpdate = `-- name: GetGatewayEnrollmentTokenForUpdate :one
SELECT id, gateway_id, token_hash, token_prefix, status, attempt_count, max_attempts, expires_at, redemption_nonce, csr_sha256, redeeming_at, lease_expires_at, consumed_at, revoked_at, created_by_user_id, created_at, updated_at FROM gateway_enrollment_tokens WHERE id = ? FOR UPDATE
`

type GetGatewayEnrollmentTokenForUpdateParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetGatewayEnrollmentTokenForUpdate(ctx context.Context, arg GetGatewayEnrollmentTokenForUpdateParams) (GatewayEnrollmentToken, error) {
	row := q.db.QueryRowContext(ctx, getGatewayEnrollmentTokenForUpdate, arg.ID)
	var i GatewayEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.RedemptionNonce,
		&i.CsrSha256,
		&i.RedeemingAt,
		&i.LeaseExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGatewayCertificate = `-- name: InsertGatewayCertificate :exec
INSERT INTO gateway_certificates
(id, gateway_id, authority_id, serial_number, certificate_pem, certificate_fingerprint, not_before, not_after, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGatewayCertificateParams struct {
	ID                     string `db:"id" json:"id"`
	GatewayID              string `db:"gateway_id" json:"gateway_id"`
	AuthorityID            string `db:"authority_id" json:"authority_id"`
	SerialNumber           string `db:"serial_number" json:"serial_number"`
	CertificatePem         string `db:"certificate_pem" json:"certificate_pem"`
	CertificateFingerprint []byte `db:"certificate_fingerprint" json:"certificate_fingerprint"`
	NotBefore              int64  `db:"not_before" json:"not_before"`
	NotAfter               int64  `db:"not_after" json:"not_after"`
	CreatedAt              int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertGatewayCertificate(ctx context.Context, arg InsertGatewayCertificateParams) error {
	_, err := q.db.ExecContext(ctx, insertGatewayCertificate,
		arg.ID,
		arg.GatewayID,
		arg.AuthorityID,
		arg.SerialNumber,
		arg.CertificatePem,
		arg.CertificateFingerprint,
		arg.NotBefore,
		arg.NotAfter,
		arg.CreatedAt,
	)
	return err
}

const issueGatewayEnrollmentToken = `-- name: IssueGatewayEnrollmentToken :exec
INSERT INTO gateway_enrollment_tokens
(id, gateway_id, token_hash, token_prefix, status, attempt_count, max_attempts, expires_at, created_by_user_id, created_at, updated_at)
VALUES (?, ?, ?, ?, 'active', 0, ?, ?, ?, ?, ?)
`

type IssueGatewayEnrollmentTokenParams struct {
	ID              string `db:"id" json:"id"`
	GatewayID       string `db:"gateway_id" json:"gateway_id"`
	TokenHash       []byte `db:"token_hash" json:"token_hash"`
	TokenPrefix     string `db:"token_prefix" json:"token_prefix"`
	MaxAttempts     uint32 `db:"max_attempts" json:"max_attempts"`
	ExpiresAt       int64  `db:"expires_at" json:"expires_at"`
	CreatedByUserID string `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       int64  `db:"created_at" json:"created_at"`
	UpdatedAt       int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) IssueGatewayEnrollmentToken(ctx context.Context, arg IssueGatewayEnrollmentTokenParams) error {
	_, err := q.db.ExecContext(ctx, issueGatewayEnrollmentToken,
		arg.ID,
		arg.GatewayID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.MaxAttempts,
		arg.ExpiresAt,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAuditEventsByResource = `-- name: ListAuditEventsByResource :many
SELECT id, organization_id, actor_type, actor_id, action, resource_type, resource_id, outcome, request_id, source_ip, metadata, created_at FROM audit_events
WHERE resource_type=? AND resource_id=? AND created_at<?
ORDER BY created_at DESC, id DESC LIMIT ?
`

type ListAuditEventsByResourceParams struct {
	ResourceType string         `db:"resource_type" json:"resource_type"`
	ResourceID   sql.NullString `db:"resource_id" json:"resource_id"`
	CreatedAt    int64          `db:"created_at" json:"created_at"`
	Limit        int32          `db:"limit" json:"limit"`
}

func (q *Queries) ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Outcome,
			&i.RequestID,
			&i.SourceIp,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewayCertificates = `-- name: ListGatewayCertificates :many
SELECT id, gateway_id, authority_id, serial_number, certificate_pem, certificate_fingerprint, not_before, not_after, revoked_at, revocation_reason, created_at FROM gateway_certificates WHERE gateway_id=? ORDER BY created_at DESC, id DESC
`

type ListGatewayCertificatesParams struct {
	GatewayID string `db:"gateway_id" json:"gateway_id"`
}

func (q *Queries) ListGatewayCertificates(ctx context.Context, arg ListGatewayCertificatesParams) ([]GatewayCertificate, error) {
	rows, err := q.db.QueryContext(ctx, listGatewayCertificates, arg.GatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GatewayCertificate{}
	for rows.Next() {
		var i GatewayCertificate
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.AuthorityID,
			&i.SerialNumber,
			&i.CertificatePem,
			&i.CertificateFingerprint,
			&i.NotBefore,
			&i.NotAfter,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGatewayEnrollmentToken = `-- name: LockGatewayEnrollmentToken :execrows
UPDATE gateway_enrollment_tokens SET status='locked', updated_at=?
  , redemption_nonce=NULL, csr_sha256=NULL, redeeming_at=NULL, lease_expires_at=NULL
WHERE id=? AND status IN ('active','redeeming')
`

type LockGatewayEnrollmentTokenParams struct {
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) LockGatewayEnrollmentToken(ctx context.Context, arg LockGatewayEnrollmentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockGatewayEnrollmentToken, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseGatewayEnrollment = `-- name: ReleaseGatewayEnrollment :execrows
UPDATE gateway_enrollment_tokens
SET status='active', redemption_nonce=NULL, csr_sha256=NULL, redeeming_at=NULL,
    lease_expires_at=NULL, updated_at=?
WHERE id=? AND status='redeeming' AND redemption_nonce=? AND csr_sha256=? AND lease_expires_at>?
`

type ReleaseGatewayEnrollmentParams struct {
	UpdatedAt       int64          `db:"updated_at" json:"updated_at"`
	ID              string         `db:"id" json:"id"`
	RedemptionNonce sql.NullString `db:"redemption_nonce" json:"redemption_nonce"`
	CsrSha256       sql.NullString `db:"csr_sha256" json:"csr_sha256"`
	LeaseExpiresAt  sql.NullInt64  `db:"lease_expires_at" json:"lease_expires_at"`
}

func (q *Queries) ReleaseGatewayEnrollment(ctx context.Context, arg ReleaseGatewayEnrollmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseGatewayEnrollment,
		arg.UpdatedAt,
		arg.ID,
		arg.RedemptionNonce,
		arg.CsrSha256,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeGatewayCertificate = `-- name: RevokeGatewayCertificate :execrows
UPDATE gateway_certificates SET revoked_at=?, revocation_reason=?
WHERE id=? AND revoked_at IS NULL
`

type RevokeGatewayCertificateParams struct {
	RevokedAt        sql.NullInt64  `db:"revoked_at" json:"revoked_at"`
	RevocationReason sql.NullString `db:"revocation_reason" json:"revocation_reason"`
	ID               string         `db:"id" json:"id"`
}

func (q *Queries) RevokeGatewayCertificate(ctx context.Context, arg RevokeGatewayCertificateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeGatewayCertificate, arg.RevokedAt, arg.RevocationReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeGatewayEnrollmentToken = `-- name: RevokeGatewayEnrollmentToken :execrows
UPDATE gateway_enrollment_tokens SET status='revoked', revoked_at=?, updated_at=?
  , redemption_nonce=NULL, csr_sha256=NULL, redeeming_at=NULL, lease_expires_at=NULL
WHERE id=? AND status IN ('active','redeeming')
`

type RevokeGatewayEnrollmentTokenParams struct {
	RevokedAt sql.NullInt64 `db:"revoked_at" json:"revoked_at"`
	UpdatedAt int64         `db:"updated_at" json:"updated_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) RevokeGatewayEnrollmentToken(ctx context.Context, arg RevokeGatewayEnrollmentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeGatewayEnrollmentToken, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
