// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package storedb

import (
	"context"
	"database/sql"
)

const getGroupByJID = `-- name: GetGroupByJID :one
SELECT id, group_jid, subject, description, owner_jid,
	participant_count, is_announce, is_locked, created_at_wa, first_seen_at, updated_at
FROM whatsapp_groups
WHERE group_jid = ?
`

type GetGroupByJIDParams struct {
	GroupJid string `db:"group_jid" json:"group_jid"`
}

func (q *Queries) GetGroupByJID(ctx context.Context, arg GetGroupByJIDParams) (WhatsappGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupByJID, arg.GroupJid)
	var i WhatsappGroup
	err := row.Scan(
		&i.ID,
		&i.GroupJid,
		&i.Subject,
		&i.Description,
		&i.OwnerJid,
		&i.ParticipantCount,
		&i.IsAnnounce,
		&i.IsLocked,
		&i.CreatedAtWa,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupMembersByContact = `-- name: ListGroupMembersByContact :many
SELECT id, session_id, group_jid, lid, tag, role, first_seen_at, last_seen_at
FROM whatsapp_group_members
WHERE session_id = ? AND lid = ?
ORDER BY id ASC
`

type ListGroupMembersByContactParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	Lid       string `db:"lid" json:"lid"`
}

func (q *Queries) ListGroupMembersByContact(ctx context.Context, arg ListGroupMembersByContactParams) ([]WhatsappGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembersByContact, arg.SessionID, arg.Lid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WhatsappGroupMember{}
	for rows.Next() {
		var i WhatsappGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.GroupJid,
			&i.Lid,
			&i.Tag,
			&i.Role,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersByGroup = `-- name: ListGroupMembersByGroup :many
SELECT id, session_id, group_jid, lid, tag, role, first_seen_at, last_seen_at
FROM whatsapp_group_members
WHERE session_id = ? AND group_jid = ?
ORDER BY id ASC
`

type ListGroupMembersByGroupParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	GroupJid  string `db:"group_jid" json:"group_jid"`
}

func (q *Queries) ListGroupMembersByGroup(ctx context.Context, arg ListGroupMembersByGroupParams) ([]WhatsappGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembersByGroup, arg.SessionID, arg.GroupJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WhatsappGroupMember{}
	for rows.Next() {
		var i WhatsappGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.GroupJid,
			&i.Lid,
			&i.Tag,
			&i.Role,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsBySession = `-- name: ListGroupsBySession :many
SELECT g.id, g.group_jid, g.subject, g.description, g.owner_jid,
	g.participant_count, g.is_announce, g.is_locked, g.created_at_wa, g.first_seen_at, g.updated_at
FROM whatsapp_groups g
WHERE g.group_jid IN (
	SELECT DISTINCT group_jid FROM whatsapp_group_members WHERE session_id = ?
)
ORDER BY g.id ASC
`

type ListGroupsBySessionParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

func (q *Queries) ListGroupsBySession(ctx context.Context, arg ListGroupsBySessionParams) ([]WhatsappGroup, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsBySession, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WhatsappGroup{}
	for rows.Next() {
		var i WhatsappGroup
		if err := rows.Scan(
			&i.ID,
			&i.GroupJid,
			&i.Subject,
			&i.Description,
			&i.OwnerJid,
			&i.ParticipantCount,
			&i.IsAnnounce,
			&i.IsLocked,
			&i.CreatedAtWa,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM whatsapp_group_members
WHERE session_id = ? AND group_jid = ? AND lid = ?
`

type RemoveGroupMemberParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	GroupJid  string `db:"group_jid" json:"group_jid"`
	Lid       string `db:"lid" json:"lid"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeGroupMember, arg.SessionID, arg.GroupJid, arg.Lid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertGroup = `-- name: UpsertGroup :exec
INSERT INTO whatsapp_groups
(group_jid, subject, description, owner_jid, participant_count, is_announce,
 is_locked, created_at_wa, first_seen_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
	subject           = COALESCE(VALUES(subject), subject),
	description       = COALESCE(VALUES(description), description),
	owner_jid         = COALESCE(VALUES(owner_jid), owner_jid),
	participant_count = COALESCE(VALUES(participant_count), participant_count),
	is_announce       = COALESCE(VALUES(is_announce), is_announce),
	is_locked         = COALESCE(VALUES(is_locked), is_locked),
	created_at_wa     = COALESCE(VALUES(created_at_wa), created_at_wa),
	updated_at        = VALUES(updated_at)
`

type UpsertGroupParams struct {
	GroupJid         string         `db:"group_jid" json:"group_jid"`
	Subject          sql.NullString `db:"subject" json:"subject"`
	Description      sql.NullString `db:"description" json:"description"`
	OwnerJid         sql.NullString `db:"owner_jid" json:"owner_jid"`
	ParticipantCount sql.NullInt32  `db:"participant_count" json:"participant_count"`
	IsAnnounce       sql.NullBool   `db:"is_announce" json:"is_announce"`
	IsLocked         sql.NullBool   `db:"is_locked" json:"is_locked"`
	CreatedAtWa      sql.NullInt64  `db:"created_at_wa" json:"created_at_wa"`
	FirstSeenAt      int64          `db:"first_seen_at" json:"first_seen_at"`
	UpdatedAt        int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroup,
		arg.GroupJid,
		arg.Subject,
		arg.Description,
		arg.OwnerJid,
		arg.ParticipantCount,
		arg.IsAnnounce,
		arg.IsLocked,
		arg.CreatedAtWa,
		arg.FirstSeenAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertGroupMember = `-- name: UpsertGroupMember :exec
INSERT INTO whatsapp_group_members
(session_id, group_jid, lid, tag, role, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
	tag          = COALESCE(VALUES(tag), tag),
	role         = VALUES(role),
	last_seen_at = VALUES(last_seen_at)
`

type UpsertGroupMemberParams struct {
	SessionID   string                   `db:"session_id" json:"session_id"`
	GroupJid    string                   `db:"group_jid" json:"group_jid"`
	Lid         string                   `db:"lid" json:"lid"`
	Tag         sql.NullString           `db:"tag" json:"tag"`
	Role        WhatsappGroupMembersRole `db:"role" json:"role"`
	FirstSeenAt int64                    `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt  int64                    `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) UpsertGroupMember(ctx context.Context, arg UpsertGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroupMember,
		arg.SessionID,
		arg.GroupJid,
		arg.Lid,
		arg.Tag,
		arg.Role,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
