// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package storedb

import (
	"context"
	"database/sql"
)

const fillIdentityNameByJID = `-- name: FillIdentityNameByJID :exec
UPDATE whatsapp_identities
SET name = ?, updated_at = ?
WHERE (lid = ? OR phone_jid = ?) AND (name IS NULL OR name = '')
`

type FillIdentityNameByJIDParams struct {
	Name      sql.NullString `db:"name" json:"name"`
	UpdatedAt int64          `db:"updated_at" json:"updated_at"`
	Lid       string         `db:"lid" json:"lid"`
	PhoneJid  sql.NullString `db:"phone_jid" json:"phone_jid"`
}

func (q *Queries) FillIdentityNameByJID(ctx context.Context, arg FillIdentityNameByJIDParams) error {
	_, err := q.db.ExecContext(ctx, fillIdentityNameByJID,
		arg.Name,
		arg.UpdatedAt,
		arg.Lid,
		arg.PhoneJid,
	)
	return err
}

const getIdentityByLID = `-- name: GetIdentityByLID :one
SELECT id, lid, phone_number, phone_jid, name, business_name, first_seen_at, updated_at
FROM whatsapp_identities
WHERE lid = ?
`

type GetIdentityByLIDParams struct {
	Lid string `db:"lid" json:"lid"`
}

func (q *Queries) GetIdentityByLID(ctx context.Context, arg GetIdentityByLIDParams) (WhatsappIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByLID, arg.Lid)
	var i WhatsappIdentity
	err := row.Scan(
		&i.ID,
		&i.Lid,
		&i.PhoneNumber,
		&i.PhoneJid,
		&i.Name,
		&i.BusinessName,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const namesForMentionJIDs = `-- name: NamesForMentionJIDs :many
SELECT lid, phone_jid, name
FROM whatsapp_identities
WHERE name IS NOT NULL
  AND name <> ''
  AND (FIND_IN_SET(lid, ?) > 0 OR FIND_IN_SET(phone_jid, ?) > 0)
`

type NamesForMentionJIDsParams struct {
	FINDINSET   string `db:"FIND_IN_SET" json:"FIND_IN_SET"`
	FINDINSET_2 string `db:"FIND_IN_SET_2" json:"FIND_IN_SET_2"`
}

type NamesForMentionJIDsRow struct {
	Lid      string         `db:"lid" json:"lid"`
	PhoneJid sql.NullString `db:"phone_jid" json:"phone_jid"`
	Name     sql.NullString `db:"name" json:"name"`
}

func (q *Queries) NamesForMentionJIDs(ctx context.Context, arg NamesForMentionJIDsParams) ([]NamesForMentionJIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, namesForMentionJIDs, arg.FINDINSET, arg.FINDINSET_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamesForMentionJIDsRow{}
	for rows.Next() {
		var i NamesForMentionJIDsRow
		if err := rows.Scan(&i.Lid, &i.PhoneJid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO whatsapp_identities
(lid, phone_number, phone_jid, name, business_name, first_seen_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
	phone_number  = COALESCE(VALUES(phone_number), phone_number),
	phone_jid     = COALESCE(VALUES(phone_jid), phone_jid),
	name          = COALESCE(VALUES(name), name),
	business_name = COALESCE(VALUES(business_name), business_name),
	updated_at    = VALUES(updated_at)
`

type UpsertIdentityParams struct {
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	PhoneJid     sql.NullString `db:"phone_jid" json:"phone_jid"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	FirstSeenAt  int64          `db:"first_seen_at" json:"first_seen_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertIdentity,
		arg.Lid,
		arg.PhoneNumber,
		arg.PhoneJid,
		arg.Name,
		arg.BusinessName,
		arg.FirstSeenAt,
		arg.UpdatedAt,
	)
	return err
}
