// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type BackfillImportsStatus string

const (
	BackfillImportsStatusRunning   BackfillImportsStatus = "running"
	BackfillImportsStatusSucceeded BackfillImportsStatus = "succeeded"
	BackfillImportsStatusFailed    BackfillImportsStatus = "failed"
)

func (e *BackfillImportsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackfillImportsStatus(s)
	case string:
		*e = BackfillImportsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BackfillImportsStatus: %T", src)
	}
	return nil
}

type NullBackfillImportsStatus struct {
	BackfillImportsStatus BackfillImportsStatus `json:"backfill_imports_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if BackfillImportsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackfillImportsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BackfillImportsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackfillImportsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackfillImportsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BackfillImportsStatus), nil
}

func (e BackfillImportsStatus) Valid() bool {
	switch e {
	case BackfillImportsStatusRunning,
		BackfillImportsStatusSucceeded,
		BackfillImportsStatusFailed:
		return true
	}
	return false
}

func AllBackfillImportsStatusValues() []BackfillImportsStatus {
	return []BackfillImportsStatus{
		BackfillImportsStatusRunning,
		BackfillImportsStatusSucceeded,
		BackfillImportsStatusFailed,
	}
}

type ChatsType string

const (
	ChatsTypeDm         ChatsType = "dm"
	ChatsTypeGroup      ChatsType = "group"
	ChatsTypeNewsletter ChatsType = "newsletter"
	ChatsTypeBroadcast  ChatsType = "broadcast"
	ChatsTypeStatus     ChatsType = "status"
)

func (e *ChatsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatsType(s)
	case string:
		*e = ChatsType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatsType: %T", src)
	}
	return nil
}

type NullChatsType struct {
	ChatsType ChatsType `json:"chats_type"`
	Valid     bool      `json:"valid"` // Valid is true if ChatsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatsType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatsType), nil
}

func (e ChatsType) Valid() bool {
	switch e {
	case ChatsTypeDm,
		ChatsTypeGroup,
		ChatsTypeNewsletter,
		ChatsTypeBroadcast,
		ChatsTypeStatus:
		return true
	}
	return false
}

func AllChatsTypeValues() []ChatsType {
	return []ChatsType{
		ChatsTypeDm,
		ChatsTypeGroup,
		ChatsTypeNewsletter,
		ChatsTypeBroadcast,
		ChatsTypeStatus,
	}
}

type MessagesDirection string

const (
	MessagesDirectionIn  MessagesDirection = "in"
	MessagesDirectionOut MessagesDirection = "out"
)

func (e *MessagesDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesDirection(s)
	case string:
		*e = MessagesDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesDirection: %T", src)
	}
	return nil
}

type NullMessagesDirection struct {
	MessagesDirection MessagesDirection `json:"messages_direction"`
	Valid             bool              `json:"valid"` // Valid is true if MessagesDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesDirection), nil
}

func (e MessagesDirection) Valid() bool {
	switch e {
	case MessagesDirectionIn,
		MessagesDirectionOut:
		return true
	}
	return false
}

func AllMessagesDirectionValues() []MessagesDirection {
	return []MessagesDirection{
		MessagesDirectionIn,
		MessagesDirectionOut,
	}
}

type MessagesStatus string

const (
	MessagesStatusPending   MessagesStatus = "pending"
	MessagesStatusSent      MessagesStatus = "sent"
	MessagesStatusDelivered MessagesStatus = "delivered"
	MessagesStatusRead      MessagesStatus = "read"
	MessagesStatusPlayed    MessagesStatus = "played"
	MessagesStatusFailed    MessagesStatus = "failed"
)

func (e *MessagesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesStatus(s)
	case string:
		*e = MessagesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesStatus: %T", src)
	}
	return nil
}

type NullMessagesStatus struct {
	MessagesStatus MessagesStatus `json:"messages_status"`
	Valid          bool           `json:"valid"` // Valid is true if MessagesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesStatus), nil
}

func (e MessagesStatus) Valid() bool {
	switch e {
	case MessagesStatusPending,
		MessagesStatusSent,
		MessagesStatusDelivered,
		MessagesStatusRead,
		MessagesStatusPlayed,
		MessagesStatusFailed:
		return true
	}
	return false
}

func AllMessagesStatusValues() []MessagesStatus {
	return []MessagesStatus{
		MessagesStatusPending,
		MessagesStatusSent,
		MessagesStatusDelivered,
		MessagesStatusRead,
		MessagesStatusPlayed,
		MessagesStatusFailed,
	}
}

type OutboxStatus string

const (
	OutboxStatusQueued  OutboxStatus = "queued"
	OutboxStatusSending OutboxStatus = "sending"
	OutboxStatusSent    OutboxStatus = "sent"
	OutboxStatusFailed  OutboxStatus = "failed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

func (e OutboxStatus) Valid() bool {
	switch e {
	case OutboxStatusQueued,
		OutboxStatusSending,
		OutboxStatusSent,
		OutboxStatusFailed:
		return true
	}
	return false
}

func AllOutboxStatusValues() []OutboxStatus {
	return []OutboxStatus{
		OutboxStatusQueued,
		OutboxStatusSending,
		OutboxStatusSent,
		OutboxStatusFailed,
	}
}

type WaSessionsStatus string

const (
	WaSessionsStatusStarting   WaSessionsStatus = "starting"
	WaSessionsStatusScanQrCode WaSessionsStatus = "scan_qr_code"
	WaSessionsStatusWorking    WaSessionsStatus = "working"
	WaSessionsStatusFailed     WaSessionsStatus = "failed"
	WaSessionsStatusStopped    WaSessionsStatus = "stopped"
	WaSessionsStatusLoggedOut  WaSessionsStatus = "logged_out"
)

func (e *WaSessionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaSessionsStatus(s)
	case string:
		*e = WaSessionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WaSessionsStatus: %T", src)
	}
	return nil
}

type NullWaSessionsStatus struct {
	WaSessionsStatus WaSessionsStatus `json:"wa_sessions_status"`
	Valid            bool             `json:"valid"` // Valid is true if WaSessionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaSessionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WaSessionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaSessionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaSessionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaSessionsStatus), nil
}

func (e WaSessionsStatus) Valid() bool {
	switch e {
	case WaSessionsStatusStarting,
		WaSessionsStatusScanQrCode,
		WaSessionsStatusWorking,
		WaSessionsStatusFailed,
		WaSessionsStatusStopped,
		WaSessionsStatusLoggedOut:
		return true
	}
	return false
}

func AllWaSessionsStatusValues() []WaSessionsStatus {
	return []WaSessionsStatus{
		WaSessionsStatusStarting,
		WaSessionsStatusScanQrCode,
		WaSessionsStatusWorking,
		WaSessionsStatusFailed,
		WaSessionsStatusStopped,
		WaSessionsStatusLoggedOut,
	}
}

type WebhookDeliveriesStatus string

const (
	WebhookDeliveriesStatusPending   WebhookDeliveriesStatus = "pending"
	WebhookDeliveriesStatusDelivered WebhookDeliveriesStatus = "delivered"
	WebhookDeliveriesStatusFailed    WebhookDeliveriesStatus = "failed"
	WebhookDeliveriesStatusDead      WebhookDeliveriesStatus = "dead"
)

func (e *WebhookDeliveriesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveriesStatus(s)
	case string:
		*e = WebhookDeliveriesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveriesStatus: %T", src)
	}
	return nil
}

type NullWebhookDeliveriesStatus struct {
	WebhookDeliveriesStatus WebhookDeliveriesStatus `json:"webhook_deliveries_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if WebhookDeliveriesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveriesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveriesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveriesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveriesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveriesStatus), nil
}

func (e WebhookDeliveriesStatus) Valid() bool {
	switch e {
	case WebhookDeliveriesStatusPending,
		WebhookDeliveriesStatusDelivered,
		WebhookDeliveriesStatusFailed,
		WebhookDeliveriesStatusDead:
		return true
	}
	return false
}

func AllWebhookDeliveriesStatusValues() []WebhookDeliveriesStatus {
	return []WebhookDeliveriesStatus{
		WebhookDeliveriesStatusPending,
		WebhookDeliveriesStatusDelivered,
		WebhookDeliveriesStatusFailed,
		WebhookDeliveriesStatusDead,
	}
}

type WhatsappGroupMembersRole string

const (
	WhatsappGroupMembersRoleMember     WhatsappGroupMembersRole = "member"
	WhatsappGroupMembersRoleAdmin      WhatsappGroupMembersRole = "admin"
	WhatsappGroupMembersRoleSuperadmin WhatsappGroupMembersRole = "superadmin"
)

func (e *WhatsappGroupMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappGroupMembersRole(s)
	case string:
		*e = WhatsappGroupMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappGroupMembersRole: %T", src)
	}
	return nil
}

type NullWhatsappGroupMembersRole struct {
	WhatsappGroupMembersRole WhatsappGroupMembersRole `json:"whatsapp_group_members_role"`
	Valid                    bool                     `json:"valid"` // Valid is true if WhatsappGroupMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappGroupMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappGroupMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappGroupMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappGroupMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappGroupMembersRole), nil
}

func (e WhatsappGroupMembersRole) Valid() bool {
	switch e {
	case WhatsappGroupMembersRoleMember,
		WhatsappGroupMembersRoleAdmin,
		WhatsappGroupMembersRoleSuperadmin:
		return true
	}
	return false
}

func AllWhatsappGroupMembersRoleValues() []WhatsappGroupMembersRole {
	return []WhatsappGroupMembersRole{
		WhatsappGroupMembersRoleMember,
		WhatsappGroupMembersRoleAdmin,
		WhatsappGroupMembersRoleSuperadmin,
	}
}

type Apikey struct {
	ID          string         `db:"id" json:"id"`
	Name        sql.NullString `db:"name" json:"name"`
	Key         string         `db:"key" json:"key"`
	ReferenceID sql.NullString `db:"reference_id" json:"reference_id"`
	Enabled     sql.NullBool   `db:"enabled" json:"enabled"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	Permissions sql.NullString `db:"permissions" json:"permissions"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	LastRequest sql.NullTime   `db:"last_request" json:"last_request"`
}

type BackfillImport struct {
	ID                string                `db:"id" json:"id"`
	SessionID         string                `db:"session_id" json:"session_id"`
	OrganizationID    string                `db:"organization_id" json:"organization_id"`
	Source            string                `db:"source" json:"source"`
	Status            BackfillImportsStatus `db:"status" json:"status"`
	Chats             int32                 `db:"chats" json:"chats"`
	Messages          int32                 `db:"messages" json:"messages"`
	Identities        int32                 `db:"identities" json:"identities"`
	GroupsCount       int32                 `db:"groups_count" json:"groups_count"`
	GroupMembers      int32                 `db:"group_members" json:"group_members"`
	SchemaFingerprint sql.NullString        `db:"schema_fingerprint" json:"schema_fingerprint"`
	Error             sql.NullString        `db:"error" json:"error"`
	CreatedAt         int64                 `db:"created_at" json:"created_at"`
	FinishedAt        sql.NullInt64         `db:"finished_at" json:"finished_at"`
}

type Chat struct {
	ID            uint64         `db:"id" json:"id"`
	SessionID     string         `db:"session_id" json:"session_id"`
	ChatJid       string         `db:"chat_jid" json:"chat_jid"`
	Type          ChatsType      `db:"type" json:"type"`
	Name          sql.NullString `db:"name" json:"name"`
	LastMessageAt sql.NullInt64  `db:"last_message_at" json:"last_message_at"`
	UnreadCount   int32          `db:"unread_count" json:"unread_count"`
	Archived      bool           `db:"archived" json:"archived"`
	Pinned        bool           `db:"pinned" json:"pinned"`
	MutedUntil    sql.NullInt64  `db:"muted_until" json:"muted_until"`
}

type EventLog struct {
	ID             uint64          `db:"id" json:"id"`
	EventID        string          `db:"event_id" json:"event_id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      string          `db:"session_id" json:"session_id"`
	Type           string          `db:"type" json:"type"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
}

type Gateway struct {
	ID           string         `db:"id" json:"id"`
	Label        sql.NullString `db:"label" json:"label"`
	BaseUrl      sql.NullString `db:"base_url" json:"base_url"`
	LastSeenAt   sql.NullInt64  `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt    int64          `db:"created_at" json:"created_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
	Status       string         `db:"status" json:"status"`
	SessionCount uint32         `db:"session_count" json:"session_count"`
	Capacity     sql.NullInt32  `db:"capacity" json:"capacity"`
}

type Message struct {
	ID              string             `db:"id" json:"id"`
	SessionID       string             `db:"session_id" json:"session_id"`
	WaMessageID     string             `db:"wa_message_id" json:"wa_message_id"`
	ChatJid         string             `db:"chat_jid" json:"chat_jid"`
	SenderLid       sql.NullString     `db:"sender_lid" json:"sender_lid"`
	SenderJid       sql.NullString     `db:"sender_jid" json:"sender_jid"`
	FromMe          bool               `db:"from_me" json:"from_me"`
	Direction       MessagesDirection  `db:"direction" json:"direction"`
	Type            string             `db:"type" json:"type"`
	Body            sql.NullString     `db:"body" json:"body"`
	QuotedMessageID sql.NullString     `db:"quoted_message_id" json:"quoted_message_id"`
	Mentions        json.RawMessage    `db:"mentions" json:"mentions"`
	HasMedia        bool               `db:"has_media" json:"has_media"`
	MediaMeta       json.RawMessage    `db:"media_meta" json:"media_meta"`
	Status          NullMessagesStatus `db:"status" json:"status"`
	AckLevel        sql.NullInt32      `db:"ack_level" json:"ack_level"`
	Error           sql.NullString     `db:"error" json:"error"`
	Edited          bool               `db:"edited" json:"edited"`
	Deleted         bool               `db:"deleted" json:"deleted"`
	Timestamp       int64              `db:"timestamp" json:"timestamp"`
	RawJson         json.RawMessage    `db:"raw_json" json:"raw_json"`
	CreatedAt       int64              `db:"created_at" json:"created_at"`
}

type Organization struct {
	ID string `db:"id" json:"id"`
}

type Outbox struct {
	ID             string          `db:"id" json:"id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      string          `db:"session_id" json:"session_id"`
	IdempotencyKey sql.NullString  `db:"idempotency_key" json:"idempotency_key"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	Status         OutboxStatus    `db:"status" json:"status"`
	Attempts       int32           `db:"attempts" json:"attempts"`
	WaMessageID    sql.NullString  `db:"wa_message_id" json:"wa_message_id"`
	Error          sql.NullString  `db:"error" json:"error"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

type Poll struct {
	ID              uint64          `db:"id" json:"id"`
	SessionID       string          `db:"session_id" json:"session_id"`
	PollMessageID   string          `db:"poll_message_id" json:"poll_message_id"`
	ChatJid         string          `db:"chat_jid" json:"chat_jid"`
	Name            sql.NullString  `db:"name" json:"name"`
	Options         json.RawMessage `db:"options" json:"options"`
	SelectableCount int32           `db:"selectable_count" json:"selectable_count"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	UpdatedAt       int64           `db:"updated_at" json:"updated_at"`
	EndTime         sql.NullInt64   `db:"end_time" json:"end_time"`
	HideVotes       bool            `db:"hide_votes" json:"hide_votes"`
	RecapEmittedAt  sql.NullInt64   `db:"recap_emitted_at" json:"recap_emitted_at"`
}

type PollVote struct {
	ID              uint64          `db:"id" json:"id"`
	SessionID       string          `db:"session_id" json:"session_id"`
	PollMessageID   string          `db:"poll_message_id" json:"poll_message_id"`
	VoterLid        string          `db:"voter_lid" json:"voter_lid"`
	SelectedOptions json.RawMessage `db:"selected_options" json:"selected_options"`
	Timestamp       int64           `db:"timestamp" json:"timestamp"`
	RawJson         json.RawMessage `db:"raw_json" json:"raw_json"`
}

type WaSession struct {
	ID              string           `db:"id" json:"id"`
	OrganizationID  string           `db:"organization_id" json:"organization_id"`
	CreatedByUserID sql.NullString   `db:"created_by_user_id" json:"created_by_user_id"`
	GatewayID       string           `db:"gateway_id" json:"gateway_id"`
	Label           sql.NullString   `db:"label" json:"label"`
	Status          WaSessionsStatus `db:"status" json:"status"`
	WaJid           sql.NullString   `db:"wa_jid" json:"wa_jid"`
	WaLid           sql.NullString   `db:"wa_lid" json:"wa_lid"`
	PhoneNumber     sql.NullString   `db:"phone_number" json:"phone_number"`
	IsAdminSession  bool             `db:"is_admin_session" json:"is_admin_session"`
	AutoRead        bool             `db:"auto_read" json:"auto_read"`
	PresenceTyping  bool             `db:"presence_typing" json:"presence_typing"`
	RatePerMin      int32            `db:"rate_per_min" json:"rate_per_min"`
	RatePerHour     int32            `db:"rate_per_hour" json:"rate_per_hour"`
	LastConnectedAt sql.NullInt64    `db:"last_connected_at" json:"last_connected_at"`
	CreatedAt       int64            `db:"created_at" json:"created_at"`
	UpdatedAt       int64            `db:"updated_at" json:"updated_at"`
}

type Webhook struct {
	ID             string          `db:"id" json:"id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      sql.NullString  `db:"session_id" json:"session_id"`
	Url            string          `db:"url" json:"url"`
	Events         json.RawMessage `db:"events" json:"events"`
	HmacSecret     []byte          `db:"hmac_secret" json:"hmac_secret"`
	CustomHeaders  json.RawMessage `db:"custom_headers" json:"custom_headers"`
	RetryPolicy    json.RawMessage `db:"retry_policy" json:"retry_policy"`
	Active         bool            `db:"active" json:"active"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

type WebhookDelivery struct {
	ID           uint64                  `db:"id" json:"id"`
	WebhookID    string                  `db:"webhook_id" json:"webhook_id"`
	EventID      string                  `db:"event_id" json:"event_id"`
	Status       WebhookDeliveriesStatus `db:"status" json:"status"`
	Attempts     int32                   `db:"attempts" json:"attempts"`
	ResponseCode sql.NullInt32           `db:"response_code" json:"response_code"`
	NextRetryAt  sql.NullInt64           `db:"next_retry_at" json:"next_retry_at"`
	LastError    sql.NullString          `db:"last_error" json:"last_error"`
	CreatedAt    int64                   `db:"created_at" json:"created_at"`
}

type WhatsappGroup struct {
	ID               uint64         `db:"id" json:"id"`
	GroupJid         string         `db:"group_jid" json:"group_jid"`
	Subject          sql.NullString `db:"subject" json:"subject"`
	Description      sql.NullString `db:"description" json:"description"`
	OwnerJid         sql.NullString `db:"owner_jid" json:"owner_jid"`
	ParticipantCount sql.NullInt32  `db:"participant_count" json:"participant_count"`
	IsAnnounce       sql.NullBool   `db:"is_announce" json:"is_announce"`
	IsLocked         sql.NullBool   `db:"is_locked" json:"is_locked"`
	CreatedAtWa      sql.NullInt64  `db:"created_at_wa" json:"created_at_wa"`
	FirstSeenAt      int64          `db:"first_seen_at" json:"first_seen_at"`
	UpdatedAt        int64          `db:"updated_at" json:"updated_at"`
}

type WhatsappGroupMember struct {
	ID          uint64                   `db:"id" json:"id"`
	SessionID   string                   `db:"session_id" json:"session_id"`
	GroupJid    string                   `db:"group_jid" json:"group_jid"`
	Lid         string                   `db:"lid" json:"lid"`
	Tag         sql.NullString           `db:"tag" json:"tag"`
	Role        WhatsappGroupMembersRole `db:"role" json:"role"`
	FirstSeenAt int64                    `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt  int64                    `db:"last_seen_at" json:"last_seen_at"`
}

type WhatsappIdentity struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	PhoneJid     sql.NullString `db:"phone_jid" json:"phone_jid"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	FirstSeenAt  int64          `db:"first_seen_at" json:"first_seen_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}
