// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type AuditEventsActorType string

const (
	AuditEventsActorTypeUser    AuditEventsActorType = "user"
	AuditEventsActorTypeGateway AuditEventsActorType = "gateway"
	AuditEventsActorTypeSystem  AuditEventsActorType = "system"
)

func (e *AuditEventsActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventsActorType(s)
	case string:
		*e = AuditEventsActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventsActorType: %T", src)
	}
	return nil
}

type NullAuditEventsActorType struct {
	AuditEventsActorType AuditEventsActorType `json:"audit_events_actor_type"`
	Valid                bool                 `json:"valid"` // Valid is true if AuditEventsActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventsActorType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventsActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventsActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventsActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventsActorType), nil
}

func (e AuditEventsActorType) Valid() bool {
	switch e {
	case AuditEventsActorTypeUser,
		AuditEventsActorTypeGateway,
		AuditEventsActorTypeSystem:
		return true
	}
	return false
}

func AllAuditEventsActorTypeValues() []AuditEventsActorType {
	return []AuditEventsActorType{
		AuditEventsActorTypeUser,
		AuditEventsActorTypeGateway,
		AuditEventsActorTypeSystem,
	}
}

type AuditEventsOutcome string

const (
	AuditEventsOutcomeSuccess AuditEventsOutcome = "success"
	AuditEventsOutcomeDenied  AuditEventsOutcome = "denied"
	AuditEventsOutcomeFailure AuditEventsOutcome = "failure"
)

func (e *AuditEventsOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventsOutcome(s)
	case string:
		*e = AuditEventsOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventsOutcome: %T", src)
	}
	return nil
}

type NullAuditEventsOutcome struct {
	AuditEventsOutcome AuditEventsOutcome `json:"audit_events_outcome"`
	Valid              bool               `json:"valid"` // Valid is true if AuditEventsOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventsOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventsOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventsOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventsOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventsOutcome), nil
}

func (e AuditEventsOutcome) Valid() bool {
	switch e {
	case AuditEventsOutcomeSuccess,
		AuditEventsOutcomeDenied,
		AuditEventsOutcomeFailure:
		return true
	}
	return false
}

func AllAuditEventsOutcomeValues() []AuditEventsOutcome {
	return []AuditEventsOutcome{
		AuditEventsOutcomeSuccess,
		AuditEventsOutcomeDenied,
		AuditEventsOutcomeFailure,
	}
}

type BackfillImportsStatus string

const (
	BackfillImportsStatusRunning   BackfillImportsStatus = "running"
	BackfillImportsStatusSucceeded BackfillImportsStatus = "succeeded"
	BackfillImportsStatusFailed    BackfillImportsStatus = "failed"
)

func (e *BackfillImportsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackfillImportsStatus(s)
	case string:
		*e = BackfillImportsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BackfillImportsStatus: %T", src)
	}
	return nil
}

type NullBackfillImportsStatus struct {
	BackfillImportsStatus BackfillImportsStatus `json:"backfill_imports_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if BackfillImportsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackfillImportsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BackfillImportsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackfillImportsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackfillImportsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BackfillImportsStatus), nil
}

func (e BackfillImportsStatus) Valid() bool {
	switch e {
	case BackfillImportsStatusRunning,
		BackfillImportsStatusSucceeded,
		BackfillImportsStatusFailed:
		return true
	}
	return false
}

func AllBackfillImportsStatusValues() []BackfillImportsStatus {
	return []BackfillImportsStatus{
		BackfillImportsStatusRunning,
		BackfillImportsStatusSucceeded,
		BackfillImportsStatusFailed,
	}
}

type ChatsType string

const (
	ChatsTypeDm         ChatsType = "dm"
	ChatsTypeGroup      ChatsType = "group"
	ChatsTypeNewsletter ChatsType = "newsletter"
	ChatsTypeBroadcast  ChatsType = "broadcast"
	ChatsTypeStatus     ChatsType = "status"
)

func (e *ChatsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatsType(s)
	case string:
		*e = ChatsType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatsType: %T", src)
	}
	return nil
}

type NullChatsType struct {
	ChatsType ChatsType `json:"chats_type"`
	Valid     bool      `json:"valid"` // Valid is true if ChatsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatsType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatsType), nil
}

func (e ChatsType) Valid() bool {
	switch e {
	case ChatsTypeDm,
		ChatsTypeGroup,
		ChatsTypeNewsletter,
		ChatsTypeBroadcast,
		ChatsTypeStatus:
		return true
	}
	return false
}

func AllChatsTypeValues() []ChatsType {
	return []ChatsType{
		ChatsTypeDm,
		ChatsTypeGroup,
		ChatsTypeNewsletter,
		ChatsTypeBroadcast,
		ChatsTypeStatus,
	}
}

type GatewayCertificatesIssuanceKind string

const (
	GatewayCertificatesIssuanceKindEnrollment GatewayCertificatesIssuanceKind = "enrollment"
	GatewayCertificatesIssuanceKindRenewal    GatewayCertificatesIssuanceKind = "renewal"
)

func (e *GatewayCertificatesIssuanceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayCertificatesIssuanceKind(s)
	case string:
		*e = GatewayCertificatesIssuanceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayCertificatesIssuanceKind: %T", src)
	}
	return nil
}

type NullGatewayCertificatesIssuanceKind struct {
	GatewayCertificatesIssuanceKind GatewayCertificatesIssuanceKind `json:"gateway_certificates_issuance_kind"`
	Valid                           bool                            `json:"valid"` // Valid is true if GatewayCertificatesIssuanceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayCertificatesIssuanceKind) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayCertificatesIssuanceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayCertificatesIssuanceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayCertificatesIssuanceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayCertificatesIssuanceKind), nil
}

func (e GatewayCertificatesIssuanceKind) Valid() bool {
	switch e {
	case GatewayCertificatesIssuanceKindEnrollment,
		GatewayCertificatesIssuanceKindRenewal:
		return true
	}
	return false
}

func AllGatewayCertificatesIssuanceKindValues() []GatewayCertificatesIssuanceKind {
	return []GatewayCertificatesIssuanceKind{
		GatewayCertificatesIssuanceKindEnrollment,
		GatewayCertificatesIssuanceKindRenewal,
	}
}

type GatewayEnrollmentTokensStatus string

const (
	GatewayEnrollmentTokensStatusActive    GatewayEnrollmentTokensStatus = "active"
	GatewayEnrollmentTokensStatusRedeeming GatewayEnrollmentTokensStatus = "redeeming"
	GatewayEnrollmentTokensStatusConsumed  GatewayEnrollmentTokensStatus = "consumed"
	GatewayEnrollmentTokensStatusRevoked   GatewayEnrollmentTokensStatus = "revoked"
	GatewayEnrollmentTokensStatusLocked    GatewayEnrollmentTokensStatus = "locked"
)

func (e *GatewayEnrollmentTokensStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayEnrollmentTokensStatus(s)
	case string:
		*e = GatewayEnrollmentTokensStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayEnrollmentTokensStatus: %T", src)
	}
	return nil
}

type NullGatewayEnrollmentTokensStatus struct {
	GatewayEnrollmentTokensStatus GatewayEnrollmentTokensStatus `json:"gateway_enrollment_tokens_status"`
	Valid                         bool                          `json:"valid"` // Valid is true if GatewayEnrollmentTokensStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayEnrollmentTokensStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayEnrollmentTokensStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayEnrollmentTokensStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayEnrollmentTokensStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayEnrollmentTokensStatus), nil
}

func (e GatewayEnrollmentTokensStatus) Valid() bool {
	switch e {
	case GatewayEnrollmentTokensStatusActive,
		GatewayEnrollmentTokensStatusRedeeming,
		GatewayEnrollmentTokensStatusConsumed,
		GatewayEnrollmentTokensStatusRevoked,
		GatewayEnrollmentTokensStatusLocked:
		return true
	}
	return false
}

func AllGatewayEnrollmentTokensStatusValues() []GatewayEnrollmentTokensStatus {
	return []GatewayEnrollmentTokensStatus{
		GatewayEnrollmentTokensStatusActive,
		GatewayEnrollmentTokensStatusRedeeming,
		GatewayEnrollmentTokensStatusConsumed,
		GatewayEnrollmentTokensStatusRevoked,
		GatewayEnrollmentTokensStatusLocked,
	}
}

type GatewayReconciliationResultsStatus string

const (
	GatewayReconciliationResultsStatusApplied               GatewayReconciliationResultsStatus = "applied"
	GatewayReconciliationResultsStatusKeystoreMissing       GatewayReconciliationResultsStatus = "keystore_missing"
	GatewayReconciliationResultsStatusKeystoreCorrupt       GatewayReconciliationResultsStatus = "keystore_corrupt"
	GatewayReconciliationResultsStatusUnexpectedLocalDevice GatewayReconciliationResultsStatus = "unexpected_local_device"
)

func (e *GatewayReconciliationResultsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayReconciliationResultsStatus(s)
	case string:
		*e = GatewayReconciliationResultsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayReconciliationResultsStatus: %T", src)
	}
	return nil
}

type NullGatewayReconciliationResultsStatus struct {
	GatewayReconciliationResultsStatus GatewayReconciliationResultsStatus `json:"gateway_reconciliation_results_status"`
	Valid                              bool                               `json:"valid"` // Valid is true if GatewayReconciliationResultsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayReconciliationResultsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayReconciliationResultsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayReconciliationResultsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayReconciliationResultsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayReconciliationResultsStatus), nil
}

func (e GatewayReconciliationResultsStatus) Valid() bool {
	switch e {
	case GatewayReconciliationResultsStatusApplied,
		GatewayReconciliationResultsStatusKeystoreMissing,
		GatewayReconciliationResultsStatusKeystoreCorrupt,
		GatewayReconciliationResultsStatusUnexpectedLocalDevice:
		return true
	}
	return false
}

func AllGatewayReconciliationResultsStatusValues() []GatewayReconciliationResultsStatus {
	return []GatewayReconciliationResultsStatus{
		GatewayReconciliationResultsStatusApplied,
		GatewayReconciliationResultsStatusKeystoreMissing,
		GatewayReconciliationResultsStatusKeystoreCorrupt,
		GatewayReconciliationResultsStatusUnexpectedLocalDevice,
	}
}

type GatewaysConnectionMode string

const (
	GatewaysConnectionModeLegacy  GatewaysConnectionMode = "legacy"
	GatewaysConnectionModeControl GatewaysConnectionMode = "control"
)

func (e *GatewaysConnectionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewaysConnectionMode(s)
	case string:
		*e = GatewaysConnectionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewaysConnectionMode: %T", src)
	}
	return nil
}

type NullGatewaysConnectionMode struct {
	GatewaysConnectionMode GatewaysConnectionMode `json:"gateways_connection_mode"`
	Valid                  bool                   `json:"valid"` // Valid is true if GatewaysConnectionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewaysConnectionMode) Scan(value interface{}) error {
	if value == nil {
		ns.GatewaysConnectionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewaysConnectionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewaysConnectionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewaysConnectionMode), nil
}

func (e GatewaysConnectionMode) Valid() bool {
	switch e {
	case GatewaysConnectionModeLegacy,
		GatewaysConnectionModeControl:
		return true
	}
	return false
}

func AllGatewaysConnectionModeValues() []GatewaysConnectionMode {
	return []GatewaysConnectionMode{
		GatewaysConnectionModeLegacy,
		GatewaysConnectionModeControl,
	}
}

type GatewaysCreatorKind string

const (
	GatewaysCreatorKindSystem GatewaysCreatorKind = "system"
	GatewaysCreatorKindUser   GatewaysCreatorKind = "user"
)

func (e *GatewaysCreatorKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewaysCreatorKind(s)
	case string:
		*e = GatewaysCreatorKind(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewaysCreatorKind: %T", src)
	}
	return nil
}

type NullGatewaysCreatorKind struct {
	GatewaysCreatorKind GatewaysCreatorKind `json:"gateways_creator_kind"`
	Valid               bool                `json:"valid"` // Valid is true if GatewaysCreatorKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewaysCreatorKind) Scan(value interface{}) error {
	if value == nil {
		ns.GatewaysCreatorKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewaysCreatorKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewaysCreatorKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewaysCreatorKind), nil
}

func (e GatewaysCreatorKind) Valid() bool {
	switch e {
	case GatewaysCreatorKindSystem,
		GatewaysCreatorKindUser:
		return true
	}
	return false
}

func AllGatewaysCreatorKindValues() []GatewaysCreatorKind {
	return []GatewaysCreatorKind{
		GatewaysCreatorKindSystem,
		GatewaysCreatorKindUser,
	}
}

type GatewaysDesiredLifecycle string

const (
	GatewaysDesiredLifecycleRun   GatewaysDesiredLifecycle = "run"
	GatewaysDesiredLifecycleDrain GatewaysDesiredLifecycle = "drain"
)

func (e *GatewaysDesiredLifecycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewaysDesiredLifecycle(s)
	case string:
		*e = GatewaysDesiredLifecycle(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewaysDesiredLifecycle: %T", src)
	}
	return nil
}

type NullGatewaysDesiredLifecycle struct {
	GatewaysDesiredLifecycle GatewaysDesiredLifecycle `json:"gateways_desired_lifecycle"`
	Valid                    bool                     `json:"valid"` // Valid is true if GatewaysDesiredLifecycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewaysDesiredLifecycle) Scan(value interface{}) error {
	if value == nil {
		ns.GatewaysDesiredLifecycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewaysDesiredLifecycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewaysDesiredLifecycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewaysDesiredLifecycle), nil
}

func (e GatewaysDesiredLifecycle) Valid() bool {
	switch e {
	case GatewaysDesiredLifecycleRun,
		GatewaysDesiredLifecycleDrain:
		return true
	}
	return false
}

func AllGatewaysDesiredLifecycleValues() []GatewaysDesiredLifecycle {
	return []GatewaysDesiredLifecycle{
		GatewaysDesiredLifecycleRun,
		GatewaysDesiredLifecycleDrain,
	}
}

type GatewaysKeystoreIntegrity string

const (
	GatewaysKeystoreIntegrityHealthy GatewaysKeystoreIntegrity = "healthy"
	GatewaysKeystoreIntegrityMissing GatewaysKeystoreIntegrity = "missing"
	GatewaysKeystoreIntegrityCorrupt GatewaysKeystoreIntegrity = "corrupt"
)

func (e *GatewaysKeystoreIntegrity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewaysKeystoreIntegrity(s)
	case string:
		*e = GatewaysKeystoreIntegrity(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewaysKeystoreIntegrity: %T", src)
	}
	return nil
}

type NullGatewaysKeystoreIntegrity struct {
	GatewaysKeystoreIntegrity GatewaysKeystoreIntegrity `json:"gateways_keystore_integrity"`
	Valid                     bool                      `json:"valid"` // Valid is true if GatewaysKeystoreIntegrity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewaysKeystoreIntegrity) Scan(value interface{}) error {
	if value == nil {
		ns.GatewaysKeystoreIntegrity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewaysKeystoreIntegrity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewaysKeystoreIntegrity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewaysKeystoreIntegrity), nil
}

func (e GatewaysKeystoreIntegrity) Valid() bool {
	switch e {
	case GatewaysKeystoreIntegrityHealthy,
		GatewaysKeystoreIntegrityMissing,
		GatewaysKeystoreIntegrityCorrupt:
		return true
	}
	return false
}

func AllGatewaysKeystoreIntegrityValues() []GatewaysKeystoreIntegrity {
	return []GatewaysKeystoreIntegrity{
		GatewaysKeystoreIntegrityHealthy,
		GatewaysKeystoreIntegrityMissing,
		GatewaysKeystoreIntegrityCorrupt,
	}
}

type GatewaysReconciliationStatus string

const (
	GatewaysReconciliationStatusPending  GatewaysReconciliationStatus = "pending"
	GatewaysReconciliationStatusHealthy  GatewaysReconciliationStatus = "healthy"
	GatewaysReconciliationStatusDegraded GatewaysReconciliationStatus = "degraded"
)

func (e *GatewaysReconciliationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewaysReconciliationStatus(s)
	case string:
		*e = GatewaysReconciliationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewaysReconciliationStatus: %T", src)
	}
	return nil
}

type NullGatewaysReconciliationStatus struct {
	GatewaysReconciliationStatus GatewaysReconciliationStatus `json:"gateways_reconciliation_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if GatewaysReconciliationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewaysReconciliationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GatewaysReconciliationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewaysReconciliationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewaysReconciliationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewaysReconciliationStatus), nil
}

func (e GatewaysReconciliationStatus) Valid() bool {
	switch e {
	case GatewaysReconciliationStatusPending,
		GatewaysReconciliationStatusHealthy,
		GatewaysReconciliationStatusDegraded:
		return true
	}
	return false
}

func AllGatewaysReconciliationStatusValues() []GatewaysReconciliationStatus {
	return []GatewaysReconciliationStatus{
		GatewaysReconciliationStatusPending,
		GatewaysReconciliationStatusHealthy,
		GatewaysReconciliationStatusDegraded,
	}
}

type GatewaysStatus string

const (
	GatewaysStatusPendingEnrollment GatewaysStatus = "pending_enrollment"
	GatewaysStatusJoining           GatewaysStatus = "joining"
	GatewaysStatusActive            GatewaysStatus = "active"
	GatewaysStatusDraining          GatewaysStatus = "draining"
	GatewaysStatusDrained           GatewaysStatus = "drained"
	GatewaysStatusDegraded          GatewaysStatus = "degraded"
	GatewaysStatusDisabled          GatewaysStatus = "disabled"
)

func (e *GatewaysStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewaysStatus(s)
	case string:
		*e = GatewaysStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewaysStatus: %T", src)
	}
	return nil
}

type NullGatewaysStatus struct {
	GatewaysStatus GatewaysStatus `json:"gateways_status"`
	Valid          bool           `json:"valid"` // Valid is true if GatewaysStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewaysStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GatewaysStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewaysStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewaysStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewaysStatus), nil
}

func (e GatewaysStatus) Valid() bool {
	switch e {
	case GatewaysStatusPendingEnrollment,
		GatewaysStatusJoining,
		GatewaysStatusActive,
		GatewaysStatusDraining,
		GatewaysStatusDrained,
		GatewaysStatusDegraded,
		GatewaysStatusDisabled:
		return true
	}
	return false
}

func AllGatewaysStatusValues() []GatewaysStatus {
	return []GatewaysStatus{
		GatewaysStatusPendingEnrollment,
		GatewaysStatusJoining,
		GatewaysStatusActive,
		GatewaysStatusDraining,
		GatewaysStatusDrained,
		GatewaysStatusDegraded,
		GatewaysStatusDisabled,
	}
}

type MessagesDirection string

const (
	MessagesDirectionIn  MessagesDirection = "in"
	MessagesDirectionOut MessagesDirection = "out"
)

func (e *MessagesDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesDirection(s)
	case string:
		*e = MessagesDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesDirection: %T", src)
	}
	return nil
}

type NullMessagesDirection struct {
	MessagesDirection MessagesDirection `json:"messages_direction"`
	Valid             bool              `json:"valid"` // Valid is true if MessagesDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesDirection), nil
}

func (e MessagesDirection) Valid() bool {
	switch e {
	case MessagesDirectionIn,
		MessagesDirectionOut:
		return true
	}
	return false
}

func AllMessagesDirectionValues() []MessagesDirection {
	return []MessagesDirection{
		MessagesDirectionIn,
		MessagesDirectionOut,
	}
}

type MessagesStatus string

const (
	MessagesStatusPending   MessagesStatus = "pending"
	MessagesStatusSent      MessagesStatus = "sent"
	MessagesStatusDelivered MessagesStatus = "delivered"
	MessagesStatusRead      MessagesStatus = "read"
	MessagesStatusPlayed    MessagesStatus = "played"
	MessagesStatusFailed    MessagesStatus = "failed"
)

func (e *MessagesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesStatus(s)
	case string:
		*e = MessagesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesStatus: %T", src)
	}
	return nil
}

type NullMessagesStatus struct {
	MessagesStatus MessagesStatus `json:"messages_status"`
	Valid          bool           `json:"valid"` // Valid is true if MessagesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesStatus), nil
}

func (e MessagesStatus) Valid() bool {
	switch e {
	case MessagesStatusPending,
		MessagesStatusSent,
		MessagesStatusDelivered,
		MessagesStatusRead,
		MessagesStatusPlayed,
		MessagesStatusFailed:
		return true
	}
	return false
}

func AllMessagesStatusValues() []MessagesStatus {
	return []MessagesStatus{
		MessagesStatusPending,
		MessagesStatusSent,
		MessagesStatusDelivered,
		MessagesStatusRead,
		MessagesStatusPlayed,
		MessagesStatusFailed,
	}
}

type OutboxStatus string

const (
	OutboxStatusQueued  OutboxStatus = "queued"
	OutboxStatusSending OutboxStatus = "sending"
	OutboxStatusSent    OutboxStatus = "sent"
	OutboxStatusFailed  OutboxStatus = "failed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

func (e OutboxStatus) Valid() bool {
	switch e {
	case OutboxStatusQueued,
		OutboxStatusSending,
		OutboxStatusSent,
		OutboxStatusFailed:
		return true
	}
	return false
}

func AllOutboxStatusValues() []OutboxStatus {
	return []OutboxStatus{
		OutboxStatusQueued,
		OutboxStatusSending,
		OutboxStatusSent,
		OutboxStatusFailed,
	}
}

type PkiAuthoritiesKind string

const (
	PkiAuthoritiesKindRoot         PkiAuthoritiesKind = "root"
	PkiAuthoritiesKindIntermediate PkiAuthoritiesKind = "intermediate"
)

func (e *PkiAuthoritiesKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PkiAuthoritiesKind(s)
	case string:
		*e = PkiAuthoritiesKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PkiAuthoritiesKind: %T", src)
	}
	return nil
}

type NullPkiAuthoritiesKind struct {
	PkiAuthoritiesKind PkiAuthoritiesKind `json:"pki_authorities_kind"`
	Valid              bool               `json:"valid"` // Valid is true if PkiAuthoritiesKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPkiAuthoritiesKind) Scan(value interface{}) error {
	if value == nil {
		ns.PkiAuthoritiesKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PkiAuthoritiesKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPkiAuthoritiesKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PkiAuthoritiesKind), nil
}

func (e PkiAuthoritiesKind) Valid() bool {
	switch e {
	case PkiAuthoritiesKindRoot,
		PkiAuthoritiesKindIntermediate:
		return true
	}
	return false
}

func AllPkiAuthoritiesKindValues() []PkiAuthoritiesKind {
	return []PkiAuthoritiesKind{
		PkiAuthoritiesKindRoot,
		PkiAuthoritiesKindIntermediate,
	}
}

type PkiAuthoritiesParentKind string

const (
	PkiAuthoritiesParentKindRoot         PkiAuthoritiesParentKind = "root"
	PkiAuthoritiesParentKindIntermediate PkiAuthoritiesParentKind = "intermediate"
)

func (e *PkiAuthoritiesParentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PkiAuthoritiesParentKind(s)
	case string:
		*e = PkiAuthoritiesParentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PkiAuthoritiesParentKind: %T", src)
	}
	return nil
}

type NullPkiAuthoritiesParentKind struct {
	PkiAuthoritiesParentKind PkiAuthoritiesParentKind `json:"pki_authorities_parent_kind"`
	Valid                    bool                     `json:"valid"` // Valid is true if PkiAuthoritiesParentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPkiAuthoritiesParentKind) Scan(value interface{}) error {
	if value == nil {
		ns.PkiAuthoritiesParentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PkiAuthoritiesParentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPkiAuthoritiesParentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PkiAuthoritiesParentKind), nil
}

func (e PkiAuthoritiesParentKind) Valid() bool {
	switch e {
	case PkiAuthoritiesParentKindRoot,
		PkiAuthoritiesParentKindIntermediate:
		return true
	}
	return false
}

func AllPkiAuthoritiesParentKindValues() []PkiAuthoritiesParentKind {
	return []PkiAuthoritiesParentKind{
		PkiAuthoritiesParentKindRoot,
		PkiAuthoritiesParentKindIntermediate,
	}
}

type PkiAuthoritiesStatus string

const (
	PkiAuthoritiesStatusActive   PkiAuthoritiesStatus = "active"
	PkiAuthoritiesStatusRetiring PkiAuthoritiesStatus = "retiring"
	PkiAuthoritiesStatusRetired  PkiAuthoritiesStatus = "retired"
	PkiAuthoritiesStatusRevoked  PkiAuthoritiesStatus = "revoked"
)

func (e *PkiAuthoritiesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PkiAuthoritiesStatus(s)
	case string:
		*e = PkiAuthoritiesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PkiAuthoritiesStatus: %T", src)
	}
	return nil
}

type NullPkiAuthoritiesStatus struct {
	PkiAuthoritiesStatus PkiAuthoritiesStatus `json:"pki_authorities_status"`
	Valid                bool                 `json:"valid"` // Valid is true if PkiAuthoritiesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPkiAuthoritiesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PkiAuthoritiesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PkiAuthoritiesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPkiAuthoritiesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PkiAuthoritiesStatus), nil
}

func (e PkiAuthoritiesStatus) Valid() bool {
	switch e {
	case PkiAuthoritiesStatusActive,
		PkiAuthoritiesStatusRetiring,
		PkiAuthoritiesStatusRetired,
		PkiAuthoritiesStatusRevoked:
		return true
	}
	return false
}

func AllPkiAuthoritiesStatusValues() []PkiAuthoritiesStatus {
	return []PkiAuthoritiesStatus{
		PkiAuthoritiesStatusActive,
		PkiAuthoritiesStatusRetiring,
		PkiAuthoritiesStatusRetired,
		PkiAuthoritiesStatusRevoked,
	}
}

type WaSessionsStatus string

const (
	WaSessionsStatusStarting   WaSessionsStatus = "starting"
	WaSessionsStatusScanQrCode WaSessionsStatus = "scan_qr_code"
	WaSessionsStatusWorking    WaSessionsStatus = "working"
	WaSessionsStatusFailed     WaSessionsStatus = "failed"
	WaSessionsStatusStopped    WaSessionsStatus = "stopped"
	WaSessionsStatusLoggedOut  WaSessionsStatus = "logged_out"
)

func (e *WaSessionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaSessionsStatus(s)
	case string:
		*e = WaSessionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WaSessionsStatus: %T", src)
	}
	return nil
}

type NullWaSessionsStatus struct {
	WaSessionsStatus WaSessionsStatus `json:"wa_sessions_status"`
	Valid            bool             `json:"valid"` // Valid is true if WaSessionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaSessionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WaSessionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaSessionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaSessionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaSessionsStatus), nil
}

func (e WaSessionsStatus) Valid() bool {
	switch e {
	case WaSessionsStatusStarting,
		WaSessionsStatusScanQrCode,
		WaSessionsStatusWorking,
		WaSessionsStatusFailed,
		WaSessionsStatusStopped,
		WaSessionsStatusLoggedOut:
		return true
	}
	return false
}

func AllWaSessionsStatusValues() []WaSessionsStatus {
	return []WaSessionsStatus{
		WaSessionsStatusStarting,
		WaSessionsStatusScanQrCode,
		WaSessionsStatusWorking,
		WaSessionsStatusFailed,
		WaSessionsStatusStopped,
		WaSessionsStatusLoggedOut,
	}
}

type WebhookDeliveriesStatus string

const (
	WebhookDeliveriesStatusPending   WebhookDeliveriesStatus = "pending"
	WebhookDeliveriesStatusDelivered WebhookDeliveriesStatus = "delivered"
	WebhookDeliveriesStatusFailed    WebhookDeliveriesStatus = "failed"
	WebhookDeliveriesStatusDead      WebhookDeliveriesStatus = "dead"
)

func (e *WebhookDeliveriesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveriesStatus(s)
	case string:
		*e = WebhookDeliveriesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveriesStatus: %T", src)
	}
	return nil
}

type NullWebhookDeliveriesStatus struct {
	WebhookDeliveriesStatus WebhookDeliveriesStatus `json:"webhook_deliveries_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if WebhookDeliveriesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveriesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveriesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveriesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveriesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveriesStatus), nil
}

func (e WebhookDeliveriesStatus) Valid() bool {
	switch e {
	case WebhookDeliveriesStatusPending,
		WebhookDeliveriesStatusDelivered,
		WebhookDeliveriesStatusFailed,
		WebhookDeliveriesStatusDead:
		return true
	}
	return false
}

func AllWebhookDeliveriesStatusValues() []WebhookDeliveriesStatus {
	return []WebhookDeliveriesStatus{
		WebhookDeliveriesStatusPending,
		WebhookDeliveriesStatusDelivered,
		WebhookDeliveriesStatusFailed,
		WebhookDeliveriesStatusDead,
	}
}

type WhatsappGroupMembersRole string

const (
	WhatsappGroupMembersRoleMember     WhatsappGroupMembersRole = "member"
	WhatsappGroupMembersRoleAdmin      WhatsappGroupMembersRole = "admin"
	WhatsappGroupMembersRoleSuperadmin WhatsappGroupMembersRole = "superadmin"
)

func (e *WhatsappGroupMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappGroupMembersRole(s)
	case string:
		*e = WhatsappGroupMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappGroupMembersRole: %T", src)
	}
	return nil
}

type NullWhatsappGroupMembersRole struct {
	WhatsappGroupMembersRole WhatsappGroupMembersRole `json:"whatsapp_group_members_role"`
	Valid                    bool                     `json:"valid"` // Valid is true if WhatsappGroupMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappGroupMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappGroupMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappGroupMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappGroupMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappGroupMembersRole), nil
}

func (e WhatsappGroupMembersRole) Valid() bool {
	switch e {
	case WhatsappGroupMembersRoleMember,
		WhatsappGroupMembersRoleAdmin,
		WhatsappGroupMembersRoleSuperadmin:
		return true
	}
	return false
}

func AllWhatsappGroupMembersRoleValues() []WhatsappGroupMembersRole {
	return []WhatsappGroupMembersRole{
		WhatsappGroupMembersRoleMember,
		WhatsappGroupMembersRoleAdmin,
		WhatsappGroupMembersRoleSuperadmin,
	}
}

type Apikey struct {
	ID          string         `db:"id" json:"id"`
	Name        sql.NullString `db:"name" json:"name"`
	Key         string         `db:"key" json:"key"`
	ReferenceID sql.NullString `db:"reference_id" json:"reference_id"`
	Enabled     sql.NullBool   `db:"enabled" json:"enabled"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	Permissions sql.NullString `db:"permissions" json:"permissions"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	LastRequest sql.NullTime   `db:"last_request" json:"last_request"`
}

type AuditEvent struct {
	ID             string               `db:"id" json:"id"`
	OrganizationID sql.NullString       `db:"organization_id" json:"organization_id"`
	ActorType      AuditEventsActorType `db:"actor_type" json:"actor_type"`
	ActorID        sql.NullString       `db:"actor_id" json:"actor_id"`
	Action         string               `db:"action" json:"action"`
	ResourceType   string               `db:"resource_type" json:"resource_type"`
	ResourceID     sql.NullString       `db:"resource_id" json:"resource_id"`
	Outcome        AuditEventsOutcome   `db:"outcome" json:"outcome"`
	RequestID      sql.NullString       `db:"request_id" json:"request_id"`
	SourceIp       sql.NullString       `db:"source_ip" json:"source_ip"`
	Metadata       json.RawMessage      `db:"metadata" json:"metadata"`
	CreatedAt      int64                `db:"created_at" json:"created_at"`
}

type BackfillImport struct {
	ID                string                `db:"id" json:"id"`
	SessionID         string                `db:"session_id" json:"session_id"`
	OrganizationID    string                `db:"organization_id" json:"organization_id"`
	Source            string                `db:"source" json:"source"`
	Status            BackfillImportsStatus `db:"status" json:"status"`
	Chats             int32                 `db:"chats" json:"chats"`
	Messages          int32                 `db:"messages" json:"messages"`
	Identities        int32                 `db:"identities" json:"identities"`
	GroupsCount       int32                 `db:"groups_count" json:"groups_count"`
	GroupMembers      int32                 `db:"group_members" json:"group_members"`
	SchemaFingerprint sql.NullString        `db:"schema_fingerprint" json:"schema_fingerprint"`
	Error             sql.NullString        `db:"error" json:"error"`
	CreatedAt         int64                 `db:"created_at" json:"created_at"`
	FinishedAt        sql.NullInt64         `db:"finished_at" json:"finished_at"`
}

type Chat struct {
	ID            uint64         `db:"id" json:"id"`
	SessionID     string         `db:"session_id" json:"session_id"`
	ChatJid       string         `db:"chat_jid" json:"chat_jid"`
	Type          ChatsType      `db:"type" json:"type"`
	Name          sql.NullString `db:"name" json:"name"`
	LastMessageAt sql.NullInt64  `db:"last_message_at" json:"last_message_at"`
	UnreadCount   int32          `db:"unread_count" json:"unread_count"`
	Archived      bool           `db:"archived" json:"archived"`
	Pinned        bool           `db:"pinned" json:"pinned"`
	MutedUntil    sql.NullInt64  `db:"muted_until" json:"muted_until"`
}

type EventLog struct {
	ID             uint64          `db:"id" json:"id"`
	EventID        string          `db:"event_id" json:"event_id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      string          `db:"session_id" json:"session_id"`
	Type           string          `db:"type" json:"type"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
}

type Gateway struct {
	ID                   string                        `db:"id" json:"id"`
	Label                sql.NullString                `db:"label" json:"label"`
	Notes                sql.NullString                `db:"notes" json:"notes"`
	Status               GatewaysStatus                `db:"status" json:"status"`
	DesiredLifecycle     GatewaysDesiredLifecycle      `db:"desired_lifecycle" json:"desired_lifecycle"`
	ConnectionMode       GatewaysConnectionMode        `db:"connection_mode" json:"connection_mode"`
	CreatorKind          GatewaysCreatorKind           `db:"creator_kind" json:"creator_kind"`
	CreatedByUserID      sql.NullString                `db:"created_by_user_id" json:"created_by_user_id"`
	BaseUrl              sql.NullString                `db:"base_url" json:"base_url"`
	GrpcEndpoint         sql.NullString                `db:"grpc_endpoint" json:"grpc_endpoint"`
	SessionCount         uint32                        `db:"session_count" json:"session_count"`
	Capacity             sql.NullInt32                 `db:"capacity" json:"capacity"`
	DesiredRevision      uint64                        `db:"desired_revision" json:"desired_revision"`
	AppliedRevision      uint64                        `db:"applied_revision" json:"applied_revision"`
	SoftwareVersion      sql.NullString                `db:"software_version" json:"software_version"`
	Capabilities         json.RawMessage               `db:"capabilities" json:"capabilities"`
	ConnectionEpoch      uint64                        `db:"connection_epoch" json:"connection_epoch"`
	EnrolledAt           sql.NullInt64                 `db:"enrolled_at" json:"enrolled_at"`
	ConnectedAt          sql.NullInt64                 `db:"connected_at" json:"connected_at"`
	LastSeenAt           sql.NullInt64                 `db:"last_seen_at" json:"last_seen_at"`
	DeletedAt            sql.NullInt64                 `db:"deleted_at" json:"deleted_at"`
	CreatedAt            int64                         `db:"created_at" json:"created_at"`
	UpdatedAt            int64                         `db:"updated_at" json:"updated_at"`
	ReconciliationStatus GatewaysReconciliationStatus  `db:"reconciliation_status" json:"reconciliation_status"`
	KeystorePresent      sql.NullBool                  `db:"keystore_present" json:"keystore_present"`
	KeystoreBytes        sql.NullInt64                 `db:"keystore_bytes" json:"keystore_bytes"`
	KeystoreIntegrity    NullGatewaysKeystoreIntegrity `db:"keystore_integrity" json:"keystore_integrity"`
	KeystoreCheckedAt    sql.NullInt64                 `db:"keystore_checked_at" json:"keystore_checked_at"`
}

type GatewayCertificate struct {
	ID                     string                          `db:"id" json:"id"`
	GatewayID              string                          `db:"gateway_id" json:"gateway_id"`
	AuthorityID            string                          `db:"authority_id" json:"authority_id"`
	IssuanceKind           GatewayCertificatesIssuanceKind `db:"issuance_kind" json:"issuance_kind"`
	EnrollmentTokenID      sql.NullString                  `db:"enrollment_token_id" json:"enrollment_token_id"`
	CsrSha256              []byte                          `db:"csr_sha256" json:"csr_sha256"`
	SerialNumber           string                          `db:"serial_number" json:"serial_number"`
	CertificatePem         string                          `db:"certificate_pem" json:"certificate_pem"`
	TrustBundlePem         string                          `db:"trust_bundle_pem" json:"trust_bundle_pem"`
	CertificateFingerprint []byte                          `db:"certificate_fingerprint" json:"certificate_fingerprint"`
	NotBefore              int64                           `db:"not_before" json:"not_before"`
	NotAfter               int64                           `db:"not_after" json:"not_after"`
	RevokedAt              sql.NullInt64                   `db:"revoked_at" json:"revoked_at"`
	RevocationReason       sql.NullString                  `db:"revocation_reason" json:"revocation_reason"`
	CreatedAt              int64                           `db:"created_at" json:"created_at"`
}

type GatewayEnrollmentToken struct {
	ID              string                        `db:"id" json:"id"`
	GatewayID       string                        `db:"gateway_id" json:"gateway_id"`
	TokenHash       []byte                        `db:"token_hash" json:"token_hash"`
	TokenPrefix     string                        `db:"token_prefix" json:"token_prefix"`
	Status          GatewayEnrollmentTokensStatus `db:"status" json:"status"`
	AttemptCount    uint32                        `db:"attempt_count" json:"attempt_count"`
	MaxAttempts     uint32                        `db:"max_attempts" json:"max_attempts"`
	ExpiresAt       int64                         `db:"expires_at" json:"expires_at"`
	RedemptionNonce sql.NullString                `db:"redemption_nonce" json:"redemption_nonce"`
	CsrSha256       sql.NullString                `db:"csr_sha256" json:"csr_sha256"`
	RedeemingAt     sql.NullInt64                 `db:"redeeming_at" json:"redeeming_at"`
	LeaseExpiresAt  sql.NullInt64                 `db:"lease_expires_at" json:"lease_expires_at"`
	ConsumedAt      sql.NullInt64                 `db:"consumed_at" json:"consumed_at"`
	RevokedAt       sql.NullInt64                 `db:"revoked_at" json:"revoked_at"`
	CreatedByUserID string                        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       int64                         `db:"created_at" json:"created_at"`
	UpdatedAt       int64                         `db:"updated_at" json:"updated_at"`
}

type GatewayIngestedEvent struct {
	GatewayEventID  string `db:"gateway_event_id" json:"gateway_event_id"`
	GatewayID       string `db:"gateway_id" json:"gateway_id"`
	ConnectionEpoch uint64 `db:"connection_epoch" json:"connection_epoch"`
	SessionID       string `db:"session_id" json:"session_id"`
	AssignmentEpoch uint64 `db:"assignment_epoch" json:"assignment_epoch"`
	OrganizationID  string `db:"organization_id" json:"organization_id"`
	EventLogID      string `db:"event_log_id" json:"event_log_id"`
	CommittedAt     int64  `db:"committed_at" json:"committed_at"`
}

type GatewayReconciliationResult struct {
	ID              uint64                             `db:"id" json:"id"`
	GatewayID       string                             `db:"gateway_id" json:"gateway_id"`
	DeviceJid       sql.NullString                     `db:"device_jid" json:"device_jid"`
	SessionID       sql.NullString                     `db:"session_id" json:"session_id"`
	AssignmentEpoch uint64                             `db:"assignment_epoch" json:"assignment_epoch"`
	Status          GatewayReconciliationResultsStatus `db:"status" json:"status"`
	DesiredRevision uint64                             `db:"desired_revision" json:"desired_revision"`
	UpdatedAt       int64                              `db:"updated_at" json:"updated_at"`
}

type GatewaySessionAssignment struct {
	SessionID       string `db:"session_id" json:"session_id"`
	GatewayID       string `db:"gateway_id" json:"gateway_id"`
	AssignmentEpoch uint64 `db:"assignment_epoch" json:"assignment_epoch"`
	CreatedAt       int64  `db:"created_at" json:"created_at"`
	UpdatedAt       int64  `db:"updated_at" json:"updated_at"`
}

type Message struct {
	ID              string             `db:"id" json:"id"`
	SessionID       string             `db:"session_id" json:"session_id"`
	WaMessageID     string             `db:"wa_message_id" json:"wa_message_id"`
	ChatJid         string             `db:"chat_jid" json:"chat_jid"`
	SenderLid       sql.NullString     `db:"sender_lid" json:"sender_lid"`
	SenderJid       sql.NullString     `db:"sender_jid" json:"sender_jid"`
	FromMe          bool               `db:"from_me" json:"from_me"`
	Direction       MessagesDirection  `db:"direction" json:"direction"`
	Type            string             `db:"type" json:"type"`
	Body            sql.NullString     `db:"body" json:"body"`
	QuotedMessageID sql.NullString     `db:"quoted_message_id" json:"quoted_message_id"`
	Mentions        json.RawMessage    `db:"mentions" json:"mentions"`
	HasMedia        bool               `db:"has_media" json:"has_media"`
	MediaMeta       json.RawMessage    `db:"media_meta" json:"media_meta"`
	Status          NullMessagesStatus `db:"status" json:"status"`
	AckLevel        sql.NullInt32      `db:"ack_level" json:"ack_level"`
	Error           sql.NullString     `db:"error" json:"error"`
	Edited          bool               `db:"edited" json:"edited"`
	Deleted         bool               `db:"deleted" json:"deleted"`
	Timestamp       int64              `db:"timestamp" json:"timestamp"`
	RawJson         json.RawMessage    `db:"raw_json" json:"raw_json"`
	CreatedAt       int64              `db:"created_at" json:"created_at"`
}

type Organization struct {
	ID string `db:"id" json:"id"`
}

type Outbox struct {
	ID             string          `db:"id" json:"id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      string          `db:"session_id" json:"session_id"`
	IdempotencyKey sql.NullString  `db:"idempotency_key" json:"idempotency_key"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	Status         OutboxStatus    `db:"status" json:"status"`
	Attempts       int32           `db:"attempts" json:"attempts"`
	WaMessageID    sql.NullString  `db:"wa_message_id" json:"wa_message_id"`
	Error          sql.NullString  `db:"error" json:"error"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

type PkiAuthority struct {
	ID                     string                       `db:"id" json:"id"`
	Kind                   PkiAuthoritiesKind           `db:"kind" json:"kind"`
	ParentAuthorityID      sql.NullString               `db:"parent_authority_id" json:"parent_authority_id"`
	ParentKind             NullPkiAuthoritiesParentKind `db:"parent_kind" json:"parent_kind"`
	Status                 PkiAuthoritiesStatus         `db:"status" json:"status"`
	CertificatePem         string                       `db:"certificate_pem" json:"certificate_pem"`
	CertificateFingerprint []byte                       `db:"certificate_fingerprint" json:"certificate_fingerprint"`
	EncryptedPrivateKey    []byte                       `db:"encrypted_private_key" json:"encrypted_private_key"`
	PrivateKeyNonce        []byte                       `db:"private_key_nonce" json:"private_key_nonce"`
	EncryptionKeyID        string                       `db:"encryption_key_id" json:"encryption_key_id"`
	NotBefore              int64                        `db:"not_before" json:"not_before"`
	NotAfter               int64                        `db:"not_after" json:"not_after"`
	CreatedAt              int64                        `db:"created_at" json:"created_at"`
	UpdatedAt              int64                        `db:"updated_at" json:"updated_at"`
	ActiveKind             sql.NullString               `db:"active_kind" json:"active_kind"`
}

type PkiRotationLock struct {
	ID int8 `db:"id" json:"id"`
}

type Poll struct {
	ID              uint64          `db:"id" json:"id"`
	SessionID       string          `db:"session_id" json:"session_id"`
	PollMessageID   string          `db:"poll_message_id" json:"poll_message_id"`
	ChatJid         string          `db:"chat_jid" json:"chat_jid"`
	Name            sql.NullString  `db:"name" json:"name"`
	Options         json.RawMessage `db:"options" json:"options"`
	SelectableCount int32           `db:"selectable_count" json:"selectable_count"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	UpdatedAt       int64           `db:"updated_at" json:"updated_at"`
	EndTime         sql.NullInt64   `db:"end_time" json:"end_time"`
	HideVotes       bool            `db:"hide_votes" json:"hide_votes"`
	RecapEmittedAt  sql.NullInt64   `db:"recap_emitted_at" json:"recap_emitted_at"`
}

type PollVote struct {
	ID              uint64          `db:"id" json:"id"`
	SessionID       string          `db:"session_id" json:"session_id"`
	PollMessageID   string          `db:"poll_message_id" json:"poll_message_id"`
	VoterLid        string          `db:"voter_lid" json:"voter_lid"`
	SelectedOptions json.RawMessage `db:"selected_options" json:"selected_options"`
	Timestamp       int64           `db:"timestamp" json:"timestamp"`
	RawJson         json.RawMessage `db:"raw_json" json:"raw_json"`
}

type WaSession struct {
	ID              string           `db:"id" json:"id"`
	OrganizationID  string           `db:"organization_id" json:"organization_id"`
	CreatedByUserID sql.NullString   `db:"created_by_user_id" json:"created_by_user_id"`
	GatewayID       string           `db:"gateway_id" json:"gateway_id"`
	Label           sql.NullString   `db:"label" json:"label"`
	Status          WaSessionsStatus `db:"status" json:"status"`
	WaJid           sql.NullString   `db:"wa_jid" json:"wa_jid"`
	WaLid           sql.NullString   `db:"wa_lid" json:"wa_lid"`
	PhoneNumber     sql.NullString   `db:"phone_number" json:"phone_number"`
	IsAdminSession  bool             `db:"is_admin_session" json:"is_admin_session"`
	AutoRead        bool             `db:"auto_read" json:"auto_read"`
	PresenceTyping  bool             `db:"presence_typing" json:"presence_typing"`
	RatePerMin      int32            `db:"rate_per_min" json:"rate_per_min"`
	RatePerHour     int32            `db:"rate_per_hour" json:"rate_per_hour"`
	LastConnectedAt sql.NullInt64    `db:"last_connected_at" json:"last_connected_at"`
	CreatedAt       int64            `db:"created_at" json:"created_at"`
	UpdatedAt       int64            `db:"updated_at" json:"updated_at"`
}

type Webhook struct {
	ID             string          `db:"id" json:"id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      sql.NullString  `db:"session_id" json:"session_id"`
	Url            string          `db:"url" json:"url"`
	Events         json.RawMessage `db:"events" json:"events"`
	HmacSecret     []byte          `db:"hmac_secret" json:"hmac_secret"`
	CustomHeaders  json.RawMessage `db:"custom_headers" json:"custom_headers"`
	RetryPolicy    json.RawMessage `db:"retry_policy" json:"retry_policy"`
	Active         bool            `db:"active" json:"active"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

type WebhookDelivery struct {
	ID           uint64                  `db:"id" json:"id"`
	WebhookID    string                  `db:"webhook_id" json:"webhook_id"`
	EventID      string                  `db:"event_id" json:"event_id"`
	Status       WebhookDeliveriesStatus `db:"status" json:"status"`
	Attempts     int32                   `db:"attempts" json:"attempts"`
	ResponseCode sql.NullInt32           `db:"response_code" json:"response_code"`
	NextRetryAt  sql.NullInt64           `db:"next_retry_at" json:"next_retry_at"`
	LastError    sql.NullString          `db:"last_error" json:"last_error"`
	CreatedAt    int64                   `db:"created_at" json:"created_at"`
}

type WhatsappGroup struct {
	ID               uint64         `db:"id" json:"id"`
	GroupJid         string         `db:"group_jid" json:"group_jid"`
	Subject          sql.NullString `db:"subject" json:"subject"`
	Description      sql.NullString `db:"description" json:"description"`
	OwnerJid         sql.NullString `db:"owner_jid" json:"owner_jid"`
	ParticipantCount sql.NullInt32  `db:"participant_count" json:"participant_count"`
	IsAnnounce       sql.NullBool   `db:"is_announce" json:"is_announce"`
	IsLocked         sql.NullBool   `db:"is_locked" json:"is_locked"`
	CreatedAtWa      sql.NullInt64  `db:"created_at_wa" json:"created_at_wa"`
	FirstSeenAt      int64          `db:"first_seen_at" json:"first_seen_at"`
	UpdatedAt        int64          `db:"updated_at" json:"updated_at"`
}

type WhatsappGroupMember struct {
	ID          uint64                   `db:"id" json:"id"`
	SessionID   string                   `db:"session_id" json:"session_id"`
	GroupJid    string                   `db:"group_jid" json:"group_jid"`
	Lid         string                   `db:"lid" json:"lid"`
	Tag         sql.NullString           `db:"tag" json:"tag"`
	Role        WhatsappGroupMembersRole `db:"role" json:"role"`
	FirstSeenAt int64                    `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt  int64                    `db:"last_seen_at" json:"last_seen_at"`
}

type WhatsappIdentity struct {
	ID           uint64         `db:"id" json:"id"`
	Lid          string         `db:"lid" json:"lid"`
	PhoneNumber  sql.NullString `db:"phone_number" json:"phone_number"`
	PhoneJid     sql.NullString `db:"phone_jid" json:"phone_jid"`
	Name         sql.NullString `db:"name" json:"name"`
	BusinessName sql.NullString `db:"business_name" json:"business_name"`
	FirstSeenAt  int64          `db:"first_seen_at" json:"first_seen_at"`
	UpdatedAt    int64          `db:"updated_at" json:"updated_at"`
}
