// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package storedb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const claimQueuedOutbox = `-- name: ClaimQueuedOutbox :exec
UPDATE outbox
SET status = ?, attempts = attempts + 1, updated_at = ?
WHERE status = ?
ORDER BY created_at ASC
LIMIT ?
`

type ClaimQueuedOutboxParams struct {
	Status    OutboxStatus `db:"status" json:"status"`
	UpdatedAt int64        `db:"updated_at" json:"updated_at"`
	Status_2  OutboxStatus `db:"status_2" json:"status_2"`
	Limit     int32        `db:"limit" json:"limit"`
}

func (q *Queries) ClaimQueuedOutbox(ctx context.Context, arg ClaimQueuedOutboxParams) error {
	_, err := q.db.ExecContext(ctx, claimQueuedOutbox,
		arg.Status,
		arg.UpdatedAt,
		arg.Status_2,
		arg.Limit,
	)
	return err
}

const getOutbox = `-- name: GetOutbox :one
SELECT id, organization_id, session_id, idempotency_key, payload, status,
	attempts, wa_message_id, error, created_at, updated_at
FROM outbox
WHERE id = ?
`

type GetOutboxParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetOutbox(ctx context.Context, arg GetOutboxParams) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, getOutbox, arg.ID)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.WaMessageID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxByIdempotency = `-- name: GetOutboxByIdempotency :one
SELECT id, organization_id, session_id, idempotency_key, payload, status,
	attempts, wa_message_id, error, created_at, updated_at
FROM outbox
WHERE organization_id = ? AND idempotency_key = ?
`

type GetOutboxByIdempotencyParams struct {
	OrganizationID string         `db:"organization_id" json:"organization_id"`
	IdempotencyKey sql.NullString `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetOutboxByIdempotency(ctx context.Context, arg GetOutboxByIdempotencyParams) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, getOutboxByIdempotency, arg.OrganizationID, arg.IdempotencyKey)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.WaMessageID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox
(id, organization_id, session_id, idempotency_key, payload, status, attempts,
 wa_message_id, error, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOutboxParams struct {
	ID             string          `db:"id" json:"id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      string          `db:"session_id" json:"session_id"`
	IdempotencyKey sql.NullString  `db:"idempotency_key" json:"idempotency_key"`
	Payload        json.RawMessage `db:"payload" json:"payload"`
	Status         OutboxStatus    `db:"status" json:"status"`
	Attempts       int32           `db:"attempts" json:"attempts"`
	WaMessageID    sql.NullString  `db:"wa_message_id" json:"wa_message_id"`
	Error          sql.NullString  `db:"error" json:"error"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.WaMessageID,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listClaimedOutbox = `-- name: ListClaimedOutbox :many
SELECT id, organization_id, session_id, idempotency_key, payload, status,
	attempts, wa_message_id, error, created_at, updated_at
FROM outbox
WHERE status = ? AND updated_at = ?
ORDER BY created_at ASC
LIMIT ?
`

type ListClaimedOutboxParams struct {
	Status    OutboxStatus `db:"status" json:"status"`
	UpdatedAt int64        `db:"updated_at" json:"updated_at"`
	Limit     int32        `db:"limit" json:"limit"`
}

func (q *Queries) ListClaimedOutbox(ctx context.Context, arg ListClaimedOutboxParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, listClaimedOutbox, arg.Status, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.IdempotencyKey,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.WaMessageID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxStatus = `-- name: UpdateOutboxStatus :execrows
UPDATE outbox
SET status = ?, wa_message_id = ?, error = ?, updated_at = ?
WHERE id = ?
`

type UpdateOutboxStatusParams struct {
	Status      OutboxStatus   `db:"status" json:"status"`
	WaMessageID sql.NullString `db:"wa_message_id" json:"wa_message_id"`
	Error       sql.NullString `db:"error" json:"error"`
	UpdatedAt   int64          `db:"updated_at" json:"updated_at"`
	ID          string         `db:"id" json:"id"`
}

func (q *Queries) UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOutboxStatus,
		arg.Status,
		arg.WaMessageID,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOutboxStatusAndStripMedia = `-- name: UpdateOutboxStatusAndStripMedia :execrows
UPDATE outbox
SET status = ?, wa_message_id = ?, error = ?, updated_at = ?,
	payload = JSON_REMOVE(payload, '$.media.data')
WHERE id = ?
`

type UpdateOutboxStatusAndStripMediaParams struct {
	Status      OutboxStatus   `db:"status" json:"status"`
	WaMessageID sql.NullString `db:"wa_message_id" json:"wa_message_id"`
	Error       sql.NullString `db:"error" json:"error"`
	UpdatedAt   int64          `db:"updated_at" json:"updated_at"`
	ID          string         `db:"id" json:"id"`
}

func (q *Queries) UpdateOutboxStatusAndStripMedia(ctx context.Context, arg UpdateOutboxStatusAndStripMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOutboxStatusAndStripMedia,
		arg.Status,
		arg.WaMessageID,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
