// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: poll.sql

package storedb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getPollOptions = `-- name: GetPollOptions :one
SELECT options
FROM polls
WHERE session_id = ? AND poll_message_id = ?
`

type GetPollOptionsParams struct {
	SessionID     string `db:"session_id" json:"session_id"`
	PollMessageID string `db:"poll_message_id" json:"poll_message_id"`
}

func (q *Queries) GetPollOptions(ctx context.Context, arg GetPollOptionsParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getPollOptions, arg.SessionID, arg.PollMessageID)
	var options json.RawMessage
	err := row.Scan(&options)
	return options, err
}

const insertPollVote = `-- name: InsertPollVote :execresult
INSERT IGNORE INTO poll_votes
(session_id, poll_message_id, voter_lid, selected_options, timestamp, raw_json)
VALUES (?, ?, ?, ?, ?, NULLIF(?, ''))
`

type InsertPollVoteParams struct {
	SessionID       string          `db:"session_id" json:"session_id"`
	PollMessageID   string          `db:"poll_message_id" json:"poll_message_id"`
	VoterLid        string          `db:"voter_lid" json:"voter_lid"`
	SelectedOptions json.RawMessage `db:"selected_options" json:"selected_options"`
	Timestamp       int64           `db:"timestamp" json:"timestamp"`
	RawJson         interface{}     `db:"raw_json" json:"raw_json"`
}

func (q *Queries) InsertPollVote(ctx context.Context, arg InsertPollVoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPollVote,
		arg.SessionID,
		arg.PollMessageID,
		arg.VoterLid,
		arg.SelectedOptions,
		arg.Timestamp,
		arg.RawJson,
	)
}

const listPollVotesByPoll = `-- name: ListPollVotesByPoll :many
SELECT id, session_id, poll_message_id, voter_lid, selected_options, timestamp, COALESCE(raw_json, '') AS raw_json
FROM poll_votes
WHERE session_id = ? AND poll_message_id = ?
ORDER BY id ASC
`

type ListPollVotesByPollParams struct {
	SessionID     string `db:"session_id" json:"session_id"`
	PollMessageID string `db:"poll_message_id" json:"poll_message_id"`
}

func (q *Queries) ListPollVotesByPoll(ctx context.Context, arg ListPollVotesByPollParams) ([]PollVote, error) {
	rows, err := q.db.QueryContext(ctx, listPollVotesByPoll, arg.SessionID, arg.PollMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollVote{}
	for rows.Next() {
		var i PollVote
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PollMessageID,
			&i.VoterLid,
			&i.SelectedOptions,
			&i.Timestamp,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPoll = `-- name: UpsertPoll :exec
INSERT INTO polls
(session_id, poll_message_id, chat_jid, name, options, selectable_count, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
	chat_jid         = VALUES(chat_jid),
	name             = VALUES(name),
	options          = VALUES(options),
	selectable_count = VALUES(selectable_count),
	updated_at       = VALUES(updated_at)
`

type UpsertPollParams struct {
	SessionID       string          `db:"session_id" json:"session_id"`
	PollMessageID   string          `db:"poll_message_id" json:"poll_message_id"`
	ChatJid         string          `db:"chat_jid" json:"chat_jid"`
	Name            sql.NullString  `db:"name" json:"name"`
	Options         json.RawMessage `db:"options" json:"options"`
	SelectableCount int32           `db:"selectable_count" json:"selectable_count"`
	CreatedAt       int64           `db:"created_at" json:"created_at"`
	UpdatedAt       int64           `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertPoll(ctx context.Context, arg UpsertPollParams) error {
	_, err := q.db.ExecContext(ctx, upsertPoll,
		arg.SessionID,
		arg.PollMessageID,
		arg.ChatJid,
		arg.Name,
		arg.Options,
		arg.SelectableCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
