// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package storedb

import (
	"context"
)

const deleteMessagesBefore = `-- name: DeleteMessagesBefore :execrows
DELETE FROM messages
WHERE timestamp < ?
ORDER BY timestamp, id
LIMIT ?
`

type DeleteMessagesBeforeParams struct {
	Timestamp int64 `db:"timestamp" json:"timestamp"`
	Limit     int32 `db:"limit" json:"limit"`
}

func (q *Queries) DeleteMessagesBefore(ctx context.Context, arg DeleteMessagesBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessagesBefore, arg.Timestamp, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTerminalWebhookDeliveriesBefore = `-- name: DeleteTerminalWebhookDeliveriesBefore :execrows
DELETE FROM webhook_deliveries
WHERE created_at < ?
  AND status IN (?, ?)
ORDER BY created_at, id
LIMIT ?
`

type DeleteTerminalWebhookDeliveriesBeforeParams struct {
	CreatedAt int64                   `db:"created_at" json:"created_at"`
	Status    WebhookDeliveriesStatus `db:"status" json:"status"`
	Status_2  WebhookDeliveriesStatus `db:"status_2" json:"status_2"`
	Limit     int32                   `db:"limit" json:"limit"`
}

func (q *Queries) DeleteTerminalWebhookDeliveriesBefore(ctx context.Context, arg DeleteTerminalWebhookDeliveriesBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTerminalWebhookDeliveriesBefore,
		arg.CreatedAt,
		arg.Status,
		arg.Status_2,
		arg.Limit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnreferencedEventLogBefore = `-- name: DeleteUnreferencedEventLogBefore :execrows
DELETE FROM event_log
WHERE event_log.created_at < ?
  AND NOT EXISTS (
    SELECT 1
    FROM webhook_deliveries
    WHERE webhook_deliveries.event_id = event_log.event_id
      AND webhook_deliveries.status IN (?, ?)
  )
ORDER BY created_at, id
LIMIT ?
`

type DeleteUnreferencedEventLogBeforeParams struct {
	CreatedAt int64                   `db:"created_at" json:"created_at"`
	Status    WebhookDeliveriesStatus `db:"status" json:"status"`
	Status_2  WebhookDeliveriesStatus `db:"status_2" json:"status_2"`
	Limit     int32                   `db:"limit" json:"limit"`
}

func (q *Queries) DeleteUnreferencedEventLogBefore(ctx context.Context, arg DeleteUnreferencedEventLogBeforeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedEventLogBefore,
		arg.CreatedAt,
		arg.Status,
		arg.Status_2,
		arg.Limit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
