// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package storedb

import (
	"context"
	"database/sql"
)

const countSessionsByGateway = `-- name: CountSessionsByGateway :one
SELECT COUNT(*) FROM wa_sessions WHERE gateway_id = ?
`

type CountSessionsByGatewayParams struct {
	GatewayID string `db:"gateway_id" json:"gateway_id"`
}

func (q *Queries) CountSessionsByGateway(ctx context.Context, arg CountSessionsByGatewayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByGateway, arg.GatewayID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO wa_sessions
(id, organization_id, created_by_user_id, gateway_id, label, status, wa_jid, wa_lid,
 phone_number, is_admin_session, auto_read, presence_typing, rate_per_min, rate_per_hour,
 last_connected_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID              string           `db:"id" json:"id"`
	OrganizationID  string           `db:"organization_id" json:"organization_id"`
	CreatedByUserID sql.NullString   `db:"created_by_user_id" json:"created_by_user_id"`
	GatewayID       string           `db:"gateway_id" json:"gateway_id"`
	Label           sql.NullString   `db:"label" json:"label"`
	Status          WaSessionsStatus `db:"status" json:"status"`
	WaJid           sql.NullString   `db:"wa_jid" json:"wa_jid"`
	WaLid           sql.NullString   `db:"wa_lid" json:"wa_lid"`
	PhoneNumber     sql.NullString   `db:"phone_number" json:"phone_number"`
	IsAdminSession  bool             `db:"is_admin_session" json:"is_admin_session"`
	AutoRead        bool             `db:"auto_read" json:"auto_read"`
	PresenceTyping  bool             `db:"presence_typing" json:"presence_typing"`
	RatePerMin      int32            `db:"rate_per_min" json:"rate_per_min"`
	RatePerHour     int32            `db:"rate_per_hour" json:"rate_per_hour"`
	LastConnectedAt sql.NullInt64    `db:"last_connected_at" json:"last_connected_at"`
	CreatedAt       int64            `db:"created_at" json:"created_at"`
	UpdatedAt       int64            `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.OrganizationID,
		arg.CreatedByUserID,
		arg.GatewayID,
		arg.Label,
		arg.Status,
		arg.WaJid,
		arg.WaLid,
		arg.PhoneNumber,
		arg.IsAdminSession,
		arg.AutoRead,
		arg.PresenceTyping,
		arg.RatePerMin,
		arg.RatePerHour,
		arg.LastConnectedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM wa_sessions WHERE id = ?
`

type DeleteSessionParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, organization_id, created_by_user_id, gateway_id, label, status,
	wa_jid, wa_lid, phone_number, is_admin_session, auto_read, presence_typing,
	rate_per_min, rate_per_hour, last_connected_at, created_at, updated_at
FROM wa_sessions
WHERE id = ?
`

type GetSessionParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (WaSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID)
	var i WaSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.GatewayID,
		&i.Label,
		&i.Status,
		&i.WaJid,
		&i.WaLid,
		&i.PhoneNumber,
		&i.IsAdminSession,
		&i.AutoRead,
		&i.PresenceTyping,
		&i.RatePerMin,
		&i.RatePerHour,
		&i.LastConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByJID = `-- name: GetSessionByJID :one
SELECT id, organization_id, created_by_user_id, gateway_id, label, status,
	wa_jid, wa_lid, phone_number, is_admin_session, auto_read, presence_typing,
	rate_per_min, rate_per_hour, last_connected_at, created_at, updated_at
FROM wa_sessions
WHERE wa_jid = ?
`

type GetSessionByJIDParams struct {
	WaJid sql.NullString `db:"wa_jid" json:"wa_jid"`
}

func (q *Queries) GetSessionByJID(ctx context.Context, arg GetSessionByJIDParams) (WaSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByJID, arg.WaJid)
	var i WaSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.GatewayID,
		&i.Label,
		&i.Status,
		&i.WaJid,
		&i.WaLid,
		&i.PhoneNumber,
		&i.IsAdminSession,
		&i.AutoRead,
		&i.PresenceTyping,
		&i.RatePerMin,
		&i.RatePerHour,
		&i.LastConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT id, organization_id, created_by_user_id, gateway_id, label, status,
	wa_jid, wa_lid, phone_number, is_admin_session, auto_read, presence_typing,
	rate_per_min, rate_per_hour, last_connected_at, created_at, updated_at
FROM wa_sessions
ORDER BY created_at DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]WaSession, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaSession{}
	for rows.Next() {
		var i WaSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedByUserID,
			&i.GatewayID,
			&i.Label,
			&i.Status,
			&i.WaJid,
			&i.WaLid,
			&i.PhoneNumber,
			&i.IsAdminSession,
			&i.AutoRead,
			&i.PresenceTyping,
			&i.RatePerMin,
			&i.RatePerHour,
			&i.LastConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByGateway = `-- name: ListSessionsByGateway :many
SELECT id, organization_id, created_by_user_id, gateway_id, label, status,
	wa_jid, wa_lid, phone_number, is_admin_session, auto_read, presence_typing,
	rate_per_min, rate_per_hour, last_connected_at, created_at, updated_at
FROM wa_sessions
WHERE gateway_id = ?
ORDER BY created_at ASC
`

type ListSessionsByGatewayParams struct {
	GatewayID string `db:"gateway_id" json:"gateway_id"`
}

func (q *Queries) ListSessionsByGateway(ctx context.Context, arg ListSessionsByGatewayParams) ([]WaSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByGateway, arg.GatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaSession{}
	for rows.Next() {
		var i WaSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedByUserID,
			&i.GatewayID,
			&i.Label,
			&i.Status,
			&i.WaJid,
			&i.WaLid,
			&i.PhoneNumber,
			&i.IsAdminSession,
			&i.AutoRead,
			&i.PresenceTyping,
			&i.RatePerMin,
			&i.RatePerHour,
			&i.LastConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByOrg = `-- name: ListSessionsByOrg :many
SELECT id, organization_id, created_by_user_id, gateway_id, label, status,
	wa_jid, wa_lid, phone_number, is_admin_session, auto_read, presence_typing,
	rate_per_min, rate_per_hour, last_connected_at, created_at, updated_at
FROM wa_sessions
WHERE organization_id = ?
ORDER BY created_at DESC
`

type ListSessionsByOrgParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ListSessionsByOrg(ctx context.Context, arg ListSessionsByOrgParams) ([]WaSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByOrg, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaSession{}
	for rows.Next() {
		var i WaSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedByUserID,
			&i.GatewayID,
			&i.Label,
			&i.Status,
			&i.WaJid,
			&i.WaLid,
			&i.PhoneNumber,
			&i.IsAdminSession,
			&i.AutoRead,
			&i.PresenceTyping,
			&i.RatePerMin,
			&i.RatePerHour,
			&i.LastConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :execrows
UPDATE wa_sessions SET
	label = ?, status = ?, wa_jid = ?, wa_lid = ?, phone_number = ?, auto_read = ?,
	presence_typing = ?, rate_per_min = ?, rate_per_hour = ?, last_connected_at = ?,
	updated_at = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	Label           sql.NullString   `db:"label" json:"label"`
	Status          WaSessionsStatus `db:"status" json:"status"`
	WaJid           sql.NullString   `db:"wa_jid" json:"wa_jid"`
	WaLid           sql.NullString   `db:"wa_lid" json:"wa_lid"`
	PhoneNumber     sql.NullString   `db:"phone_number" json:"phone_number"`
	AutoRead        bool             `db:"auto_read" json:"auto_read"`
	PresenceTyping  bool             `db:"presence_typing" json:"presence_typing"`
	RatePerMin      int32            `db:"rate_per_min" json:"rate_per_min"`
	RatePerHour     int32            `db:"rate_per_hour" json:"rate_per_hour"`
	LastConnectedAt sql.NullInt64    `db:"last_connected_at" json:"last_connected_at"`
	UpdatedAt       int64            `db:"updated_at" json:"updated_at"`
	ID              string           `db:"id" json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSession,
		arg.Label,
		arg.Status,
		arg.WaJid,
		arg.WaLid,
		arg.PhoneNumber,
		arg.AutoRead,
		arg.PresenceTyping,
		arg.RatePerMin,
		arg.RatePerHour,
		arg.LastConnectedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionStatus = `-- name: UpdateSessionStatus :execrows
UPDATE wa_sessions
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status    WaSessionsStatus `db:"status" json:"status"`
	UpdatedAt int64            `db:"updated_at" json:"updated_at"`
	ID        string           `db:"id" json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
