// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package storedb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createWebhook = `-- name: CreateWebhook :exec
INSERT INTO webhooks
(id, organization_id, session_id, url, events, hmac_secret, custom_headers,
 retry_policy, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, NULLIF(?, ''), ?, ?, ?, ?)
`

type CreateWebhookParams struct {
	ID             string          `db:"id" json:"id"`
	OrganizationID string          `db:"organization_id" json:"organization_id"`
	SessionID      sql.NullString  `db:"session_id" json:"session_id"`
	Url            string          `db:"url" json:"url"`
	Events         json.RawMessage `db:"events" json:"events"`
	HmacSecret     []byte          `db:"hmac_secret" json:"hmac_secret"`
	CustomHeaders  interface{}     `db:"custom_headers" json:"custom_headers"`
	RetryPolicy    json.RawMessage `db:"retry_policy" json:"retry_policy"`
	Active         bool            `db:"active" json:"active"`
	CreatedAt      int64           `db:"created_at" json:"created_at"`
	UpdatedAt      int64           `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) error {
	_, err := q.db.ExecContext(ctx, createWebhook,
		arg.ID,
		arg.OrganizationID,
		arg.SessionID,
		arg.Url,
		arg.Events,
		arg.HmacSecret,
		arg.CustomHeaders,
		arg.RetryPolicy,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM webhooks
WHERE id = ?
`

type DeleteWebhookParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, organization_id, session_id, url, events, hmac_secret, COALESCE(custom_headers, '') AS custom_headers,
	retry_policy, active, created_at, updated_at
FROM webhooks
WHERE id = ?
`

type GetWebhookParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SessionID,
		&i.Url,
		&i.Events,
		&i.HmacSecret,
		&i.CustomHeaders,
		&i.RetryPolicy,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, organization_id, session_id, url, events, hmac_secret, COALESCE(custom_headers, '') AS custom_headers,
	retry_policy, active, created_at, updated_at
FROM webhooks
WHERE organization_id = ? AND active = 1 AND (session_id IS NULL OR session_id = ?)
ORDER BY created_at DESC
`

type ListActiveWebhooksForEventParams struct {
	OrganizationID string         `db:"organization_id" json:"organization_id"`
	SessionID      sql.NullString `db:"session_id" json:"session_id"`
}

func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, arg ListActiveWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWebhooksForEvent, arg.OrganizationID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Url,
			&i.Events,
			&i.HmacSecret,
			&i.CustomHeaders,
			&i.RetryPolicy,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByOrg = `-- name: ListWebhooksByOrg :many
SELECT id, organization_id, session_id, url, events, hmac_secret, COALESCE(custom_headers, '') AS custom_headers,
	retry_policy, active, created_at, updated_at
FROM webhooks
WHERE organization_id = ?
ORDER BY created_at DESC
`

type ListWebhooksByOrgParams struct {
	OrganizationID string `db:"organization_id" json:"organization_id"`
}

func (q *Queries) ListWebhooksByOrg(ctx context.Context, arg ListWebhooksByOrgParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooksByOrg, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SessionID,
			&i.Url,
			&i.Events,
			&i.HmacSecret,
			&i.CustomHeaders,
			&i.RetryPolicy,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :execrows
UPDATE webhooks
SET session_id = ?, url = ?, events = ?, hmac_secret = ?, custom_headers = NULLIF(?, ''),
	retry_policy = ?, active = ?, updated_at = ?
WHERE id = ?
`

type UpdateWebhookParams struct {
	SessionID     sql.NullString  `db:"session_id" json:"session_id"`
	Url           string          `db:"url" json:"url"`
	Events        json.RawMessage `db:"events" json:"events"`
	HmacSecret    []byte          `db:"hmac_secret" json:"hmac_secret"`
	CustomHeaders interface{}     `db:"custom_headers" json:"custom_headers"`
	RetryPolicy   json.RawMessage `db:"retry_policy" json:"retry_policy"`
	Active        bool            `db:"active" json:"active"`
	UpdatedAt     int64           `db:"updated_at" json:"updated_at"`
	ID            string          `db:"id" json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWebhook,
		arg.SessionID,
		arg.Url,
		arg.Events,
		arg.HmacSecret,
		arg.CustomHeaders,
		arg.RetryPolicy,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
