// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikey.sql

package storedb

import (
	"context"
	"database/sql"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, ` + "`" + `key` + "`" + `, reference_id, enabled, expires_at, permissions, created_at
FROM apikey
WHERE ` + "`" + `key` + "`" + ` = ?
`

type GetAPIKeyByHashParams struct {
	Key string `db:"key" json:"key"`
}

type GetAPIKeyByHashRow struct {
	ID          string         `db:"id" json:"id"`
	Name        sql.NullString `db:"name" json:"name"`
	Key         string         `db:"key" json:"key"`
	ReferenceID sql.NullString `db:"reference_id" json:"reference_id"`
	Enabled     sql.NullBool   `db:"enabled" json:"enabled"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	Permissions sql.NullString `db:"permissions" json:"permissions"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, arg GetAPIKeyByHashParams) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, arg.Key)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.ReferenceID,
		&i.Enabled,
		&i.ExpiresAt,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, ` + "`" + `key` + "`" + `, reference_id, enabled, expires_at, permissions, created_at
FROM apikey
WHERE id = ?
`

type GetAPIKeyByIDParams struct {
	ID string `db:"id" json:"id"`
}

type GetAPIKeyByIDRow struct {
	ID          string         `db:"id" json:"id"`
	Name        sql.NullString `db:"name" json:"name"`
	Key         string         `db:"key" json:"key"`
	ReferenceID sql.NullString `db:"reference_id" json:"reference_id"`
	Enabled     sql.NullBool   `db:"enabled" json:"enabled"`
	ExpiresAt   sql.NullTime   `db:"expires_at" json:"expires_at"`
	Permissions sql.NullString `db:"permissions" json:"permissions"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, arg.ID)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.ReferenceID,
		&i.Enabled,
		&i.ExpiresAt,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKeyLastRequest = `-- name: TouchAPIKeyLastRequest :exec
UPDATE apikey
SET last_request = ?
WHERE id = ?
`

type TouchAPIKeyLastRequestParams struct {
	LastRequest sql.NullTime `db:"last_request" json:"last_request"`
	ID          string       `db:"id" json:"id"`
}

func (q *Queries) TouchAPIKeyLastRequest(ctx context.Context, arg TouchAPIKeyLastRequestParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKeyLastRequest, arg.LastRequest, arg.ID)
	return err
}
