// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill_import.sql

package storedb

import (
	"context"
	"database/sql"
)

const finishBackfillImport = `-- name: FinishBackfillImport :execrows
UPDATE backfill_imports
SET status = ?, chats = ?, messages = ?, identities = ?, groups_count = ?,
	group_members = ?, schema_fingerprint = ?, error = ?, finished_at = ?
WHERE id = ?
`

type FinishBackfillImportParams struct {
	Status            BackfillImportsStatus `db:"status" json:"status"`
	Chats             int32                 `db:"chats" json:"chats"`
	Messages          int32                 `db:"messages" json:"messages"`
	Identities        int32                 `db:"identities" json:"identities"`
	GroupsCount       int32                 `db:"groups_count" json:"groups_count"`
	GroupMembers      int32                 `db:"group_members" json:"group_members"`
	SchemaFingerprint sql.NullString        `db:"schema_fingerprint" json:"schema_fingerprint"`
	Error             sql.NullString        `db:"error" json:"error"`
	FinishedAt        sql.NullInt64         `db:"finished_at" json:"finished_at"`
	ID                string                `db:"id" json:"id"`
}

func (q *Queries) FinishBackfillImport(ctx context.Context, arg FinishBackfillImportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishBackfillImport,
		arg.Status,
		arg.Chats,
		arg.Messages,
		arg.Identities,
		arg.GroupsCount,
		arg.GroupMembers,
		arg.SchemaFingerprint,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertBackfillImport = `-- name: InsertBackfillImport :exec
INSERT INTO backfill_imports
(id, session_id, organization_id, source, status, chats, messages, identities,
 groups_count, group_members, schema_fingerprint, error, created_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBackfillImportParams struct {
	ID                string                `db:"id" json:"id"`
	SessionID         string                `db:"session_id" json:"session_id"`
	OrganizationID    string                `db:"organization_id" json:"organization_id"`
	Source            string                `db:"source" json:"source"`
	Status            BackfillImportsStatus `db:"status" json:"status"`
	Chats             int32                 `db:"chats" json:"chats"`
	Messages          int32                 `db:"messages" json:"messages"`
	Identities        int32                 `db:"identities" json:"identities"`
	GroupsCount       int32                 `db:"groups_count" json:"groups_count"`
	GroupMembers      int32                 `db:"group_members" json:"group_members"`
	SchemaFingerprint sql.NullString        `db:"schema_fingerprint" json:"schema_fingerprint"`
	Error             sql.NullString        `db:"error" json:"error"`
	CreatedAt         int64                 `db:"created_at" json:"created_at"`
	FinishedAt        sql.NullInt64         `db:"finished_at" json:"finished_at"`
}

func (q *Queries) InsertBackfillImport(ctx context.Context, arg InsertBackfillImportParams) error {
	_, err := q.db.ExecContext(ctx, insertBackfillImport,
		arg.ID,
		arg.SessionID,
		arg.OrganizationID,
		arg.Source,
		arg.Status,
		arg.Chats,
		arg.Messages,
		arg.Identities,
		arg.GroupsCount,
		arg.GroupMembers,
		arg.SchemaFingerprint,
		arg.Error,
		arg.CreatedAt,
		arg.FinishedAt,
	)
	return err
}

const lastSuccessfulBackfillImportCreatedAt = `-- name: LastSuccessfulBackfillImportCreatedAt :one
SELECT created_at
FROM backfill_imports
WHERE session_id = ? AND status = 'succeeded'
ORDER BY created_at DESC
LIMIT 1
`

type LastSuccessfulBackfillImportCreatedAtParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

func (q *Queries) LastSuccessfulBackfillImportCreatedAt(ctx context.Context, arg LastSuccessfulBackfillImportCreatedAtParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastSuccessfulBackfillImportCreatedAt, arg.SessionID)
	var created_at int64
	err := row.Scan(&created_at)
	return created_at, err
}

const latestBackfillImportForSession = `-- name: LatestBackfillImportForSession :one
SELECT id, session_id, organization_id, source, status, chats, messages, identities,
	groups_count, group_members, schema_fingerprint, error, created_at, finished_at
FROM backfill_imports
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT 1
`

type LatestBackfillImportForSessionParams struct {
	SessionID string `db:"session_id" json:"session_id"`
}

func (q *Queries) LatestBackfillImportForSession(ctx context.Context, arg LatestBackfillImportForSessionParams) (BackfillImport, error) {
	row := q.db.QueryRowContext(ctx, latestBackfillImportForSession, arg.SessionID)
	var i BackfillImport
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrganizationID,
		&i.Source,
		&i.Status,
		&i.Chats,
		&i.Messages,
		&i.Identities,
		&i.GroupsCount,
		&i.GroupMembers,
		&i.SchemaFingerprint,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const recentRunningBackfillImportExists = `-- name: RecentRunningBackfillImportExists :one
SELECT EXISTS (
	SELECT 1
	FROM backfill_imports
	WHERE session_id = ? AND status = 'running' AND created_at >= ?
	LIMIT 1
)
`

type RecentRunningBackfillImportExistsParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) RecentRunningBackfillImportExists(ctx context.Context, arg RecentRunningBackfillImportExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, recentRunningBackfillImportExists, arg.SessionID, arg.CreatedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
