// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package storedb

import (
	"context"
	"database/sql"
)

const deleteChat = `-- name: DeleteChat :execrows
DELETE FROM chats WHERE session_id = ? AND chat_jid = ?
`

type DeleteChatParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
}

func (q *Queries) DeleteChat(ctx context.Context, arg DeleteChatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChat, arg.SessionID, arg.ChatJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChat = `-- name: GetChat :one
SELECT c.id, c.session_id, c.chat_jid, c.type,
	COALESCE(g.subject, (SELECT COALESCE(i.name, i.business_name, i.phone_number) FROM whatsapp_identities i WHERE i.lid = c.chat_jid OR i.phone_jid = c.chat_jid ORDER BY CASE WHEN i.lid = c.chat_jid THEN 0 ELSE 1 END, i.id DESC LIMIT 1), c.name) AS name,
	c.last_message_at, c.unread_count, c.archived, c.pinned, c.muted_until,
	COALESCE((SELECT JSON_ARRAY(i.lid, i.phone_jid) FROM whatsapp_identities i WHERE c.type = 'dm' AND (i.lid = c.chat_jid OR i.phone_jid = c.chat_jid) ORDER BY CASE WHEN i.lid = c.chat_jid THEN 0 ELSE 1 END, i.id DESC LIMIT 1), '') AS aliases
FROM chats c
LEFT JOIN whatsapp_groups g ON g.group_jid = c.chat_jid
WHERE c.session_id = ? AND (c.chat_jid = ? OR EXISTS (SELECT 1 FROM whatsapp_identities i WHERE (i.lid = ? OR i.phone_jid = ?) AND (c.chat_jid = i.lid OR c.chat_jid = i.phone_jid)))
ORDER BY CASE WHEN c.chat_jid = ? THEN 0 ELSE 1 END, c.last_message_at DESC, c.id DESC
LIMIT 1
`

type GetChatParams struct {
	SessionID string         `db:"session_id" json:"session_id"`
	ChatJid   string         `db:"chat_jid" json:"chat_jid"`
	Lid       string         `db:"lid" json:"lid"`
	PhoneJid  sql.NullString `db:"phone_jid" json:"phone_jid"`
	ChatJid_2 string         `db:"chat_jid_2" json:"chat_jid_2"`
}

type GetChatRow struct {
	ID            uint64         `db:"id" json:"id"`
	SessionID     string         `db:"session_id" json:"session_id"`
	ChatJid       string         `db:"chat_jid" json:"chat_jid"`
	Type          ChatsType      `db:"type" json:"type"`
	Name          sql.NullString `db:"name" json:"name"`
	LastMessageAt sql.NullInt64  `db:"last_message_at" json:"last_message_at"`
	UnreadCount   int32          `db:"unread_count" json:"unread_count"`
	Archived      bool           `db:"archived" json:"archived"`
	Pinned        bool           `db:"pinned" json:"pinned"`
	MutedUntil    sql.NullInt64  `db:"muted_until" json:"muted_until"`
	Aliases       interface{}    `db:"aliases" json:"aliases"`
}

func (q *Queries) GetChat(ctx context.Context, arg GetChatParams) (GetChatRow, error) {
	row := q.db.QueryRowContext(ctx, getChat,
		arg.SessionID,
		arg.ChatJid,
		arg.Lid,
		arg.PhoneJid,
		arg.ChatJid_2,
	)
	var i GetChatRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ChatJid,
		&i.Type,
		&i.Name,
		&i.LastMessageAt,
		&i.UnreadCount,
		&i.Archived,
		&i.Pinned,
		&i.MutedUntil,
		&i.Aliases,
	)
	return i, err
}

const listChatsBySession = `-- name: ListChatsBySession :many
SELECT c.id, c.session_id, c.chat_jid, c.type,
	COALESCE(g.subject, (SELECT COALESCE(i.name, i.business_name, i.phone_number) FROM whatsapp_identities i WHERE i.lid = c.chat_jid OR i.phone_jid = c.chat_jid ORDER BY CASE WHEN i.lid = c.chat_jid THEN 0 ELSE 1 END, i.id DESC LIMIT 1), c.name) AS name,
	c.last_message_at, c.unread_count, c.archived, c.pinned, c.muted_until,
	COALESCE((SELECT JSON_ARRAY(i.lid, i.phone_jid) FROM whatsapp_identities i WHERE c.type = 'dm' AND (i.lid = c.chat_jid OR i.phone_jid = c.chat_jid) ORDER BY CASE WHEN i.lid = c.chat_jid THEN 0 ELSE 1 END, i.id DESC LIMIT 1), '') AS aliases
FROM chats c
LEFT JOIN whatsapp_groups g ON g.group_jid = c.chat_jid
WHERE c.session_id = ? AND c.last_message_at IS NOT NULL
	AND (? = 0 OR c.last_message_at < ? OR (c.last_message_at = ? AND c.id < ?))
ORDER BY c.last_message_at DESC, c.id DESC
LIMIT ?
`

type ListChatsBySessionParams struct {
	SessionID       string        `db:"session_id" json:"session_id"`
	Column2         interface{}   `db:"column_2" json:"column_2"`
	LastMessageAt   sql.NullInt64 `db:"last_message_at" json:"last_message_at"`
	LastMessageAt_2 sql.NullInt64 `db:"last_message_at_2" json:"last_message_at_2"`
	ID              uint64        `db:"id" json:"id"`
	Limit           int32         `db:"limit" json:"limit"`
}

type ListChatsBySessionRow struct {
	ID            uint64         `db:"id" json:"id"`
	SessionID     string         `db:"session_id" json:"session_id"`
	ChatJid       string         `db:"chat_jid" json:"chat_jid"`
	Type          ChatsType      `db:"type" json:"type"`
	Name          sql.NullString `db:"name" json:"name"`
	LastMessageAt sql.NullInt64  `db:"last_message_at" json:"last_message_at"`
	UnreadCount   int32          `db:"unread_count" json:"unread_count"`
	Archived      bool           `db:"archived" json:"archived"`
	Pinned        bool           `db:"pinned" json:"pinned"`
	MutedUntil    sql.NullInt64  `db:"muted_until" json:"muted_until"`
	Aliases       interface{}    `db:"aliases" json:"aliases"`
}

func (q *Queries) ListChatsBySession(ctx context.Context, arg ListChatsBySessionParams) ([]ListChatsBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatsBySession,
		arg.SessionID,
		arg.Column2,
		arg.LastMessageAt,
		arg.LastMessageAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatsBySessionRow{}
	for rows.Next() {
		var i ListChatsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ChatJid,
			&i.Type,
			&i.Name,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.Archived,
			&i.Pinned,
			&i.MutedUntil,
			&i.Aliases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatFlags = `-- name: UpdateChatFlags :execrows
UPDATE chats SET archived = ?, pinned = ?, muted_until = ?, unread_count = ?
WHERE session_id = ? AND chat_jid = ?
`

type UpdateChatFlagsParams struct {
	Archived    bool          `db:"archived" json:"archived"`
	Pinned      bool          `db:"pinned" json:"pinned"`
	MutedUntil  sql.NullInt64 `db:"muted_until" json:"muted_until"`
	UnreadCount int32         `db:"unread_count" json:"unread_count"`
	SessionID   string        `db:"session_id" json:"session_id"`
	ChatJid     string        `db:"chat_jid" json:"chat_jid"`
}

func (q *Queries) UpdateChatFlags(ctx context.Context, arg UpdateChatFlagsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChatFlags,
		arg.Archived,
		arg.Pinned,
		arg.MutedUntil,
		arg.UnreadCount,
		arg.SessionID,
		arg.ChatJid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertChat = `-- name: UpsertChat :exec
INSERT INTO chats (session_id, chat_jid, type, name, last_message_at, unread_count, archived, pinned, muted_until)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
	name = COALESCE(VALUES(name), name),
	last_message_at = GREATEST(COALESCE(last_message_at, 0), COALESCE(VALUES(last_message_at), 0)),
	unread_count = VALUES(unread_count)
`

type UpsertChatParams struct {
	SessionID     string         `db:"session_id" json:"session_id"`
	ChatJid       string         `db:"chat_jid" json:"chat_jid"`
	Type          ChatsType      `db:"type" json:"type"`
	Name          sql.NullString `db:"name" json:"name"`
	LastMessageAt sql.NullInt64  `db:"last_message_at" json:"last_message_at"`
	UnreadCount   int32          `db:"unread_count" json:"unread_count"`
	Archived      bool           `db:"archived" json:"archived"`
	Pinned        bool           `db:"pinned" json:"pinned"`
	MutedUntil    sql.NullInt64  `db:"muted_until" json:"muted_until"`
}

func (q *Queries) UpsertChat(ctx context.Context, arg UpsertChatParams) error {
	_, err := q.db.ExecContext(ctx, upsertChat,
		arg.SessionID,
		arg.ChatJid,
		arg.Type,
		arg.Name,
		arg.LastMessageAt,
		arg.UnreadCount,
		arg.Archived,
		arg.Pinned,
		arg.MutedUntil,
	)
	return err
}
