// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_alias.sql

package storedb

import (
	"context"
	"database/sql"
)

const deleteMergedDMChatAliases = `-- name: DeleteMergedDMChatAliases :exec
DELETE alias FROM chats alias
JOIN chats canonical ON canonical.session_id = alias.session_id
WHERE canonical.chat_jid = ? AND alias.chat_jid = ?
`

type DeleteMergedDMChatAliasesParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) DeleteMergedDMChatAliases(ctx context.Context, arg DeleteMergedDMChatAliasesParams) error {
	_, err := q.db.ExecContext(ctx, deleteMergedDMChatAliases, arg.ChatJid, arg.ChatJid_2)
	return err
}

const deleteSessionDMChatAlias = `-- name: DeleteSessionDMChatAlias :exec
DELETE FROM chats WHERE session_id = ? AND chat_jid = ?
`

type DeleteSessionDMChatAliasParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
}

func (q *Queries) DeleteSessionDMChatAlias(ctx context.Context, arg DeleteSessionDMChatAliasParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionDMChatAlias, arg.SessionID, arg.ChatJid)
	return err
}

const getCanonicalChatIDForAliasMerge = `-- name: GetCanonicalChatIDForAliasMerge :one
SELECT id FROM chats WHERE session_id = ? AND chat_jid = ? LIMIT 1
`

type GetCanonicalChatIDForAliasMergeParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
}

func (q *Queries) GetCanonicalChatIDForAliasMerge(ctx context.Context, arg GetCanonicalChatIDForAliasMergeParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getCanonicalChatIDForAliasMerge, arg.SessionID, arg.ChatJid)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const mergeExistingDMChatAliases = `-- name: MergeExistingDMChatAliases :exec
UPDATE chats canonical
JOIN chats alias ON alias.session_id = canonical.session_id
SET canonical.name = COALESCE(canonical.name, alias.name),
    canonical.last_message_at = GREATEST(COALESCE(canonical.last_message_at, 0), COALESCE(alias.last_message_at, 0)),
    canonical.unread_count = GREATEST(canonical.unread_count, alias.unread_count),
    canonical.archived = canonical.archived OR alias.archived,
    canonical.pinned = canonical.pinned OR alias.pinned,
    canonical.muted_until = GREATEST(COALESCE(canonical.muted_until, 0), COALESCE(alias.muted_until, 0))
WHERE alias.chat_jid = ? AND canonical.chat_jid = ?
`

type MergeExistingDMChatAliasesParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) MergeExistingDMChatAliases(ctx context.Context, arg MergeExistingDMChatAliasesParams) error {
	_, err := q.db.ExecContext(ctx, mergeExistingDMChatAliases, arg.ChatJid, arg.ChatJid_2)
	return err
}

const mergeSessionDMChatAlias = `-- name: MergeSessionDMChatAlias :exec
UPDATE chats canonical
JOIN chats alias ON alias.session_id = canonical.session_id
SET canonical.name = COALESCE(canonical.name, alias.name),
    canonical.last_message_at = GREATEST(COALESCE(canonical.last_message_at, 0), COALESCE(alias.last_message_at, 0)),
    canonical.unread_count = GREATEST(canonical.unread_count, alias.unread_count),
    canonical.archived = canonical.archived OR alias.archived,
    canonical.pinned = canonical.pinned OR alias.pinned,
    canonical.muted_until = GREATEST(COALESCE(canonical.muted_until, 0), COALESCE(alias.muted_until, 0))
WHERE alias.chat_jid = ? AND canonical.session_id = ? AND canonical.chat_jid = ?
`

type MergeSessionDMChatAliasParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) MergeSessionDMChatAlias(ctx context.Context, arg MergeSessionDMChatAliasParams) error {
	_, err := q.db.ExecContext(ctx, mergeSessionDMChatAlias, arg.ChatJid, arg.SessionID, arg.ChatJid_2)
	return err
}

const renameDMChatAliasesWithoutCanonical = `-- name: RenameDMChatAliasesWithoutCanonical :exec
UPDATE chats alias
SET alias.chat_jid = ?
WHERE alias.chat_jid = ?
  AND NOT EXISTS (
    SELECT 1 FROM chats canonical
    WHERE canonical.session_id = alias.session_id AND canonical.chat_jid = ?
  )
`

type RenameDMChatAliasesWithoutCanonicalParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
	ChatJid_3 string `db:"chat_jid_3" json:"chat_jid_3"`
}

func (q *Queries) RenameDMChatAliasesWithoutCanonical(ctx context.Context, arg RenameDMChatAliasesWithoutCanonicalParams) error {
	_, err := q.db.ExecContext(ctx, renameDMChatAliasesWithoutCanonical, arg.ChatJid, arg.ChatJid_2, arg.ChatJid_3)
	return err
}

const renameSessionDMChatAlias = `-- name: RenameSessionDMChatAlias :exec
UPDATE chats SET chat_jid = ? WHERE session_id = ? AND chat_jid = ?
`

type RenameSessionDMChatAliasParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) RenameSessionDMChatAlias(ctx context.Context, arg RenameSessionDMChatAliasParams) error {
	_, err := q.db.ExecContext(ctx, renameSessionDMChatAlias, arg.ChatJid, arg.SessionID, arg.ChatJid_2)
	return err
}

const resolveCanonicalDMChatJID = `-- name: ResolveCanonicalDMChatJID :many
SELECT lid
FROM whatsapp_identities
WHERE phone_jid = ? AND lid <> phone_jid AND lid LIKE '%@lid'
ORDER BY id DESC
LIMIT 2
`

type ResolveCanonicalDMChatJIDParams struct {
	PhoneJid sql.NullString `db:"phone_jid" json:"phone_jid"`
}

func (q *Queries) ResolveCanonicalDMChatJID(ctx context.Context, arg ResolveCanonicalDMChatJIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, resolveCanonicalDMChatJID, arg.PhoneJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var lid string
		if err := rows.Scan(&lid); err != nil {
			return nil, err
		}
		items = append(items, lid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageDMChatAliases = `-- name: UpdateMessageDMChatAliases :exec
UPDATE messages SET chat_jid = ? WHERE chat_jid = ?
`

type UpdateMessageDMChatAliasesParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) UpdateMessageDMChatAliases(ctx context.Context, arg UpdateMessageDMChatAliasesParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageDMChatAliases, arg.ChatJid, arg.ChatJid_2)
	return err
}

const updatePollDMChatAliases = `-- name: UpdatePollDMChatAliases :exec
UPDATE polls SET chat_jid = ? WHERE chat_jid = ?
`

type UpdatePollDMChatAliasesParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) UpdatePollDMChatAliases(ctx context.Context, arg UpdatePollDMChatAliasesParams) error {
	_, err := q.db.ExecContext(ctx, updatePollDMChatAliases, arg.ChatJid, arg.ChatJid_2)
	return err
}

const updateSessionMessageDMChatAliases = `-- name: UpdateSessionMessageDMChatAliases :exec
UPDATE messages SET chat_jid = ? WHERE session_id = ? AND chat_jid = ?
`

type UpdateSessionMessageDMChatAliasesParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) UpdateSessionMessageDMChatAliases(ctx context.Context, arg UpdateSessionMessageDMChatAliasesParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionMessageDMChatAliases, arg.ChatJid, arg.SessionID, arg.ChatJid_2)
	return err
}

const updateSessionPollDMChatAliases = `-- name: UpdateSessionPollDMChatAliases :exec
UPDATE polls SET chat_jid = ? WHERE session_id = ? AND chat_jid = ?
`

type UpdateSessionPollDMChatAliasesParams struct {
	ChatJid   string `db:"chat_jid" json:"chat_jid"`
	SessionID string `db:"session_id" json:"session_id"`
	ChatJid_2 string `db:"chat_jid_2" json:"chat_jid_2"`
}

func (q *Queries) UpdateSessionPollDMChatAliases(ctx context.Context, arg UpdateSessionPollDMChatAliasesParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionPollDMChatAliases, arg.ChatJid, arg.SessionID, arg.ChatJid_2)
	return err
}
