// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package storedb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const advanceReceiptStatus = `-- name: AdvanceReceiptStatus :exec
UPDATE messages
SET
	status = CASE
		-- A failed send is terminal. Receipt traffic for an unrelated/reused WA id
		-- must not rewrite the gateway's recorded send outcome.
		WHEN status = 'failed' THEN status
		-- Receipts may be duplicated or arrive out of order. Keep the highest
		-- lifecycle state observed instead of regressing read/played to delivered.
		WHEN FIELD(COALESCE(status, 'pending'), 'pending', 'sent', 'delivered', 'read', 'played')
			< CAST(? AS SIGNED)
			THEN ?
		ELSE status
	END,
	ack_level = CASE
		WHEN ? IS NULL THEN ack_level
		WHEN ack_level IS NULL OR ? > ack_level
			THEN ?
		ELSE ack_level
	END
WHERE session_id = ? AND wa_message_id = ?
`

type AdvanceReceiptStatusParams struct {
	NextStatusRank int64              `db:"next_status_rank" json:"next_status_rank"`
	NextStatus     NullMessagesStatus `db:"next_status" json:"next_status"`
	NextAckLevel   sql.NullInt32      `db:"next_ack_level" json:"next_ack_level"`
	SessionID      string             `db:"session_id" json:"session_id"`
	WaMessageID    string             `db:"wa_message_id" json:"wa_message_id"`
}

func (q *Queries) AdvanceReceiptStatus(ctx context.Context, arg AdvanceReceiptStatusParams) error {
	_, err := q.db.ExecContext(ctx, advanceReceiptStatus,
		arg.NextStatusRank,
		arg.NextStatus,
		arg.NextAckLevel,
		arg.NextAckLevel,
		arg.NextAckLevel,
		arg.SessionID,
		arg.WaMessageID,
	)
	return err
}

const getMessageByWAID = `-- name: GetMessageByWAID :one
SELECT m.id, m.session_id, m.wa_message_id, m.chat_jid, m.sender_lid,
	m.sender_jid, m.from_me, m.direction, m.type, m.body, m.quoted_message_id,
	COALESCE(m.mentions, '') AS mentions, m.has_media, COALESCE(m.media_meta, '') AS media_meta,
	m.status, m.ack_level, m.error, m.edited, m.deleted, m.timestamp,
	COALESCE(m.raw_json, '') AS raw_json, m.created_at, i.name AS sender_name
FROM messages m
LEFT JOIN whatsapp_identities i ON i.lid = m.sender_lid
WHERE m.session_id = ? AND m.wa_message_id = ?
`

type GetMessageByWAIDParams struct {
	SessionID   string `db:"session_id" json:"session_id"`
	WaMessageID string `db:"wa_message_id" json:"wa_message_id"`
}

type GetMessageByWAIDRow struct {
	ID              string             `db:"id" json:"id"`
	SessionID       string             `db:"session_id" json:"session_id"`
	WaMessageID     string             `db:"wa_message_id" json:"wa_message_id"`
	ChatJid         string             `db:"chat_jid" json:"chat_jid"`
	SenderLid       sql.NullString     `db:"sender_lid" json:"sender_lid"`
	SenderJid       sql.NullString     `db:"sender_jid" json:"sender_jid"`
	FromMe          bool               `db:"from_me" json:"from_me"`
	Direction       MessagesDirection  `db:"direction" json:"direction"`
	Type            string             `db:"type" json:"type"`
	Body            sql.NullString     `db:"body" json:"body"`
	QuotedMessageID sql.NullString     `db:"quoted_message_id" json:"quoted_message_id"`
	Mentions        json.RawMessage    `db:"mentions" json:"mentions"`
	HasMedia        bool               `db:"has_media" json:"has_media"`
	MediaMeta       json.RawMessage    `db:"media_meta" json:"media_meta"`
	Status          NullMessagesStatus `db:"status" json:"status"`
	AckLevel        sql.NullInt32      `db:"ack_level" json:"ack_level"`
	Error           sql.NullString     `db:"error" json:"error"`
	Edited          bool               `db:"edited" json:"edited"`
	Deleted         bool               `db:"deleted" json:"deleted"`
	Timestamp       int64              `db:"timestamp" json:"timestamp"`
	RawJson         json.RawMessage    `db:"raw_json" json:"raw_json"`
	CreatedAt       int64              `db:"created_at" json:"created_at"`
	SenderName      sql.NullString     `db:"sender_name" json:"sender_name"`
}

func (q *Queries) GetMessageByWAID(ctx context.Context, arg GetMessageByWAIDParams) (GetMessageByWAIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByWAID, arg.SessionID, arg.WaMessageID)
	var i GetMessageByWAIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WaMessageID,
		&i.ChatJid,
		&i.SenderLid,
		&i.SenderJid,
		&i.FromMe,
		&i.Direction,
		&i.Type,
		&i.Body,
		&i.QuotedMessageID,
		&i.Mentions,
		&i.HasMedia,
		&i.MediaMeta,
		&i.Status,
		&i.AckLevel,
		&i.Error,
		&i.Edited,
		&i.Deleted,
		&i.Timestamp,
		&i.RawJson,
		&i.CreatedAt,
		&i.SenderName,
	)
	return i, err
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT m.id, m.session_id, m.wa_message_id, m.chat_jid, m.sender_lid,
	m.sender_jid, m.from_me, m.direction, m.type, m.body, m.quoted_message_id,
	COALESCE(m.mentions, '') AS mentions, m.has_media, COALESCE(m.media_meta, '') AS media_meta,
	m.status, m.ack_level, m.error, m.edited, m.deleted, m.timestamp,
	COALESCE(m.raw_json, '') AS raw_json, m.created_at, i.name AS sender_name
FROM messages m
LEFT JOIN whatsapp_identities i ON i.lid = m.sender_lid
WHERE m.session_id = ? AND (? = '' OR m.id < ?) AND (
	m.chat_jid = ? OR EXISTS (
		SELECT 1 FROM whatsapp_identities i2
		WHERE (i2.lid = ? OR i2.phone_jid = ?)
		  AND (m.chat_jid = i2.lid OR m.chat_jid = i2.phone_jid)
	)
)
ORDER BY m.id DESC
LIMIT ?
`

type ListMessagesByChatParams struct {
	SessionID     string         `db:"session_id" json:"session_id"`
	MessageCursor string         `db:"message_cursor" json:"message_cursor"`
	ChatJid       string         `db:"chat_jid" json:"chat_jid"`
	Lid           string         `db:"lid" json:"lid"`
	PhoneJid      sql.NullString `db:"phone_jid" json:"phone_jid"`
	Limit         int32          `db:"limit" json:"limit"`
}

type ListMessagesByChatRow struct {
	ID              string             `db:"id" json:"id"`
	SessionID       string             `db:"session_id" json:"session_id"`
	WaMessageID     string             `db:"wa_message_id" json:"wa_message_id"`
	ChatJid         string             `db:"chat_jid" json:"chat_jid"`
	SenderLid       sql.NullString     `db:"sender_lid" json:"sender_lid"`
	SenderJid       sql.NullString     `db:"sender_jid" json:"sender_jid"`
	FromMe          bool               `db:"from_me" json:"from_me"`
	Direction       MessagesDirection  `db:"direction" json:"direction"`
	Type            string             `db:"type" json:"type"`
	Body            sql.NullString     `db:"body" json:"body"`
	QuotedMessageID sql.NullString     `db:"quoted_message_id" json:"quoted_message_id"`
	Mentions        json.RawMessage    `db:"mentions" json:"mentions"`
	HasMedia        bool               `db:"has_media" json:"has_media"`
	MediaMeta       json.RawMessage    `db:"media_meta" json:"media_meta"`
	Status          NullMessagesStatus `db:"status" json:"status"`
	AckLevel        sql.NullInt32      `db:"ack_level" json:"ack_level"`
	Error           sql.NullString     `db:"error" json:"error"`
	Edited          bool               `db:"edited" json:"edited"`
	Deleted         bool               `db:"deleted" json:"deleted"`
	Timestamp       int64              `db:"timestamp" json:"timestamp"`
	RawJson         json.RawMessage    `db:"raw_json" json:"raw_json"`
	CreatedAt       int64              `db:"created_at" json:"created_at"`
	SenderName      sql.NullString     `db:"sender_name" json:"sender_name"`
}

func (q *Queries) ListMessagesByChat(ctx context.Context, arg ListMessagesByChatParams) ([]ListMessagesByChatRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChat,
		arg.SessionID,
		arg.MessageCursor,
		arg.MessageCursor,
		arg.ChatJid,
		arg.Lid,
		arg.PhoneJid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByChatRow{}
	for rows.Next() {
		var i ListMessagesByChatRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.WaMessageID,
			&i.ChatJid,
			&i.SenderLid,
			&i.SenderJid,
			&i.FromMe,
			&i.Direction,
			&i.Type,
			&i.Body,
			&i.QuotedMessageID,
			&i.Mentions,
			&i.HasMedia,
			&i.MediaMeta,
			&i.Status,
			&i.AckLevel,
			&i.Error,
			&i.Edited,
			&i.Deleted,
			&i.Timestamp,
			&i.RawJson,
			&i.CreatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageDeleted = `-- name: MarkMessageDeleted :execrows
UPDATE messages SET deleted = 1
WHERE session_id = ? AND wa_message_id = ?
`

type MarkMessageDeletedParams struct {
	SessionID   string `db:"session_id" json:"session_id"`
	WaMessageID string `db:"wa_message_id" json:"wa_message_id"`
}

func (q *Queries) MarkMessageDeleted(ctx context.Context, arg MarkMessageDeletedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageDeleted, arg.SessionID, arg.WaMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessageEdited = `-- name: MarkMessageEdited :execrows
UPDATE messages SET edited = 1, body = ?
WHERE session_id = ? AND wa_message_id = ?
`

type MarkMessageEditedParams struct {
	Body        sql.NullString `db:"body" json:"body"`
	SessionID   string         `db:"session_id" json:"session_id"`
	WaMessageID string         `db:"wa_message_id" json:"wa_message_id"`
}

func (q *Queries) MarkMessageEdited(ctx context.Context, arg MarkMessageEditedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageEdited, arg.Body, arg.SessionID, arg.WaMessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages
(id, session_id, wa_message_id, chat_jid, sender_lid, sender_jid, from_me, direction,
 type, body, quoted_message_id, mentions, has_media, media_meta, status,
 ack_level, error, edited, deleted, timestamp, raw_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULLIF(?, ''), ?, NULLIF(?, ''), ?,
 ?, ?, ?, ?, ?, NULLIF(?, ''), ?)
ON DUPLICATE KEY UPDATE
	chat_jid          = VALUES(chat_jid),
	sender_lid        = COALESCE(VALUES(sender_lid), sender_lid),
	sender_jid        = COALESCE(VALUES(sender_jid), sender_jid),
	body              = COALESCE(VALUES(body), body),
	quoted_message_id = COALESCE(VALUES(quoted_message_id), quoted_message_id),
	mentions          = COALESCE(VALUES(mentions), mentions),
	has_media         = VALUES(has_media),
	media_meta        = COALESCE(VALUES(media_meta), media_meta),
	raw_json          = COALESCE(VALUES(raw_json), raw_json)
`

type UpsertMessageParams struct {
	ID              string             `db:"id" json:"id"`
	SessionID       string             `db:"session_id" json:"session_id"`
	WaMessageID     string             `db:"wa_message_id" json:"wa_message_id"`
	ChatJid         string             `db:"chat_jid" json:"chat_jid"`
	SenderLid       sql.NullString     `db:"sender_lid" json:"sender_lid"`
	SenderJid       sql.NullString     `db:"sender_jid" json:"sender_jid"`
	FromMe          bool               `db:"from_me" json:"from_me"`
	Direction       MessagesDirection  `db:"direction" json:"direction"`
	Type            string             `db:"type" json:"type"`
	Body            sql.NullString     `db:"body" json:"body"`
	QuotedMessageID sql.NullString     `db:"quoted_message_id" json:"quoted_message_id"`
	Mentions        interface{}        `db:"mentions" json:"mentions"`
	HasMedia        bool               `db:"has_media" json:"has_media"`
	MediaMeta       interface{}        `db:"media_meta" json:"media_meta"`
	Status          NullMessagesStatus `db:"status" json:"status"`
	AckLevel        sql.NullInt32      `db:"ack_level" json:"ack_level"`
	Error           sql.NullString     `db:"error" json:"error"`
	Edited          bool               `db:"edited" json:"edited"`
	Deleted         bool               `db:"deleted" json:"deleted"`
	Timestamp       int64              `db:"timestamp" json:"timestamp"`
	RawJson         interface{}        `db:"raw_json" json:"raw_json"`
	CreatedAt       int64              `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.ID,
		arg.SessionID,
		arg.WaMessageID,
		arg.ChatJid,
		arg.SenderLid,
		arg.SenderJid,
		arg.FromMe,
		arg.Direction,
		arg.Type,
		arg.Body,
		arg.QuotedMessageID,
		arg.Mentions,
		arg.HasMedia,
		arg.MediaMeta,
		arg.Status,
		arg.AckLevel,
		arg.Error,
		arg.Edited,
		arg.Deleted,
		arg.Timestamp,
		arg.RawJson,
		arg.CreatedAt,
	)
	return err
}
