// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package storedb

import (
	"context"
)

const organizationExists = `-- name: OrganizationExists :one
SELECT EXISTS (
	SELECT 1
	FROM organization
	WHERE id = ?
	LIMIT 1
)
`

type OrganizationExistsParams struct {
	ID string `db:"id" json:"id"`
}

func (q *Queries) OrganizationExists(ctx context.Context, arg OrganizationExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, organizationExists, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
