// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_delivery.sql

package storedb

import (
	"context"
	"database/sql"
)

const claimDueWebhookDeliveries = `-- name: ClaimDueWebhookDeliveries :many
SELECT id, webhook_id, event_id, status, attempts, response_code, next_retry_at, last_error, created_at
FROM webhook_deliveries
WHERE status IN (?, ?) AND next_retry_at IS NOT NULL AND next_retry_at <= ?
ORDER BY next_retry_at ASC
LIMIT ?
FOR UPDATE SKIP LOCKED
`

type ClaimDueWebhookDeliveriesParams struct {
	Status      WebhookDeliveriesStatus `db:"status" json:"status"`
	Status_2    WebhookDeliveriesStatus `db:"status_2" json:"status_2"`
	NextRetryAt sql.NullInt64           `db:"next_retry_at" json:"next_retry_at"`
	Limit       int32                   `db:"limit" json:"limit"`
}

func (q *Queries) ClaimDueWebhookDeliveries(ctx context.Context, arg ClaimDueWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.QueryContext(ctx, claimDueWebhookDeliveries,
		arg.Status,
		arg.Status_2,
		arg.NextRetryAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.Status,
			&i.Attempts,
			&i.ResponseCode,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueWebhookDelivery = `-- name: EnqueueWebhookDelivery :execresult
INSERT INTO webhook_deliveries
(webhook_id, event_id, status, attempts, next_retry_at, created_at)
VALUES (?, ?, ?, 0, ?, ?)
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id)
`

type EnqueueWebhookDeliveryParams struct {
	WebhookID   string                  `db:"webhook_id" json:"webhook_id"`
	EventID     string                  `db:"event_id" json:"event_id"`
	Status      WebhookDeliveriesStatus `db:"status" json:"status"`
	NextRetryAt sql.NullInt64           `db:"next_retry_at" json:"next_retry_at"`
	CreatedAt   int64                   `db:"created_at" json:"created_at"`
}

func (q *Queries) EnqueueWebhookDelivery(ctx context.Context, arg EnqueueWebhookDeliveryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, enqueueWebhookDelivery,
		arg.WebhookID,
		arg.EventID,
		arg.Status,
		arg.NextRetryAt,
		arg.CreatedAt,
	)
}

const leaseWebhookDelivery = `-- name: LeaseWebhookDelivery :execrows
UPDATE webhook_deliveries
SET next_retry_at = ?
WHERE id = ?
`

type LeaseWebhookDeliveryParams struct {
	NextRetryAt sql.NullInt64 `db:"next_retry_at" json:"next_retry_at"`
	ID          uint64        `db:"id" json:"id"`
}

func (q *Queries) LeaseWebhookDelivery(ctx context.Context, arg LeaseWebhookDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, leaseWebhookDelivery, arg.NextRetryAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markWebhookDeliveryDead = `-- name: MarkWebhookDeliveryDead :execrows
UPDATE webhook_deliveries
SET status = ?, attempts = attempts + 1, response_code = ?, last_error = ?, next_retry_at = NULL
WHERE id = ?
`

type MarkWebhookDeliveryDeadParams struct {
	Status       WebhookDeliveriesStatus `db:"status" json:"status"`
	ResponseCode sql.NullInt32           `db:"response_code" json:"response_code"`
	LastError    sql.NullString          `db:"last_error" json:"last_error"`
	ID           uint64                  `db:"id" json:"id"`
}

func (q *Queries) MarkWebhookDeliveryDead(ctx context.Context, arg MarkWebhookDeliveryDeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWebhookDeliveryDead,
		arg.Status,
		arg.ResponseCode,
		arg.LastError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markWebhookDeliveryDelivered = `-- name: MarkWebhookDeliveryDelivered :execrows
UPDATE webhook_deliveries
SET status = ?, attempts = attempts + 1, response_code = ?, next_retry_at = NULL, last_error = NULL
WHERE id = ?
`

type MarkWebhookDeliveryDeliveredParams struct {
	Status       WebhookDeliveriesStatus `db:"status" json:"status"`
	ResponseCode sql.NullInt32           `db:"response_code" json:"response_code"`
	ID           uint64                  `db:"id" json:"id"`
}

func (q *Queries) MarkWebhookDeliveryDelivered(ctx context.Context, arg MarkWebhookDeliveryDeliveredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWebhookDeliveryDelivered, arg.Status, arg.ResponseCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :execrows
UPDATE webhook_deliveries
SET status = ?, attempts = attempts + 1, response_code = ?, last_error = ?, next_retry_at = ?
WHERE id = ?
`

type MarkWebhookDeliveryFailedParams struct {
	Status       WebhookDeliveriesStatus `db:"status" json:"status"`
	ResponseCode sql.NullInt32           `db:"response_code" json:"response_code"`
	LastError    sql.NullString          `db:"last_error" json:"last_error"`
	NextRetryAt  sql.NullInt64           `db:"next_retry_at" json:"next_retry_at"`
	ID           uint64                  `db:"id" json:"id"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWebhookDeliveryFailed,
		arg.Status,
		arg.ResponseCode,
		arg.LastError,
		arg.NextRetryAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const webhookDeliveryTerminalExists = `-- name: WebhookDeliveryTerminalExists :one
SELECT EXISTS (
	SELECT 1
	FROM webhook_deliveries
	WHERE webhook_id = ? AND event_id = ? AND status IN (?, ?)
	LIMIT 1
)
`

type WebhookDeliveryTerminalExistsParams struct {
	WebhookID string                  `db:"webhook_id" json:"webhook_id"`
	EventID   string                  `db:"event_id" json:"event_id"`
	Status    WebhookDeliveriesStatus `db:"status" json:"status"`
	Status_2  WebhookDeliveriesStatus `db:"status_2" json:"status_2"`
}

func (q *Queries) WebhookDeliveryTerminalExists(ctx context.Context, arg WebhookDeliveryTerminalExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, webhookDeliveryTerminalExists,
		arg.WebhookID,
		arg.EventID,
		arg.Status,
		arg.Status_2,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
