/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description 200 once the database and Redis are reachable.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This OpenAPI document */
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions */
        get: operations["listSessions"];
        put?: never;
        /** Create a session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** Get a session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Delete a session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}:start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}:stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop a session */
        post: operations["stopSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}:restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart a session */
        post: operations["restartSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}:logout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out a session (unpair the device) */
        post: operations["logoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/me": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** Get the connected account's own identity */
        get: operations["sessionMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/qr": {
        parameters: {
            query?: {
                /** @description Return a QR image instead of the raw code string. */
                format?: "image";
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** Get the current pairing QR code */
        get: operations["sessionQR"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/pairing-code": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a phone pairing code */
        post: operations["sessionPairingCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message (any supported type)
         * @description Single send endpoint discriminated on `type`. `text`, `poll`, `location` and `contact` are live in v1; `image`/`video`/`audio`/`document`/`sticker` return 501. Supports `Idempotency-Key` and `?async`.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/messages/{mid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke (delete for everyone) */
        delete: operations["revokeMessage"];
        options?: never;
        head?: never;
        /** Edit a sent text message */
        patch: operations["editMessage"];
        trace?: never;
    };
    "/sessions/{session}/messages/{mid}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a reaction */
        post: operations["addReaction"];
        /** Remove a reaction */
        delete: operations["removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/messages/{mid}/forward": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forward a message */
        post: operations["forwardMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/messages/{mid}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vote on a poll message */
        post: operations["voteMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/chats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** List chats */
        get: operations["listChats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/chats/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        /** Get a chat */
        get: operations["getChat"];
        put?: never;
        post?: never;
        /** Delete a chat */
        delete: operations["deleteChat"];
        options?: never;
        head?: never;
        /** Update a chat (archive / pin / mute) */
        patch: operations["updateChat"];
        trace?: never;
    };
    "/sessions/{session}/chats/{cid}/messages": {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        /** List messages in a chat */
        get: operations["listChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/chats/{cid}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a chat read */
        post: operations["readChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/chats/{cid}/presence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Send a chat presence (typing / recording) */
        put: operations["chatPresence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** List found-user contacts */
        get: operations["listContacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts/check": {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** Check whether a phone number is on WhatsApp */
        get: operations["checkContact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts/{lid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                lid: string;
            };
            cookie?: never;
        };
        /** Get a contact (identity + DM + group memberships) */
        get: operations["getContact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts/{jid}/picture": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        /** Get a contact's profile picture */
        get: operations["contactPicture"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts/{jid}/about": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        /** Get a contact's about/status text */
        get: operations["contactAbout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts/{jid}/block": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block a contact */
        post: operations["blockContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/contacts/{jid}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock a contact */
        post: operations["unblockContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        /** List groups */
        get: operations["listGroups"];
        put?: never;
        /** Create a group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups:join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a group by invite link/code */
        post: operations["joinGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        /** Get a group */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update group settings */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}:leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave a group */
        post: operations["leaveGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        /** List group members */
        get: operations["listGroupMembers"];
        put?: never;
        /** Add members */
        post: operations["addGroupMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}/members:approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve pending join requests (not in v1) */
        post: operations["approveGroupMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}/members/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}/members/{jid}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote a member to admin */
        post: operations["promoteGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}/members/{jid}/demote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demote an admin to member */
        post: operations["demoteGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/groups/{gid}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        /** Get the group invite link */
        get: operations["getGroupInvite"];
        put?: never;
        post?: never;
        /** Revoke (reset) the group invite link */
        delete: operations["revokeGroupInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a channel (newsletter) — not in v1 */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/channels/{jid}:follow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow a channel — not in v1 */
        post: operations["followChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/channels/{jid}:unfollow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unfollow a channel — not in v1 */
        post: operations["unfollowChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/channels/{jid}:mute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mute a channel — not in v1 */
        post: operations["muteChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/channels/{jid}/messages": {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        /** List stored channel messages */
        get: operations["listChannelMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post a status update (text; media returns 501) */
        post: operations["postStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session}/presence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        get?: never;
        /** Set account presence (online / offline) */
        put: operations["setPresence"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream events (NDJSON)
         * @description Long-lived NDJSON stream of the §9 event envelope. Requires the `events` capability: an api-key with the `events` permission, or a JWT (any role). Scoped to the caller's organization.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhooks */
        get: operations["listWebhooks"];
        put?: never;
        /** Create a webhook */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        /** Get a webhook */
        get: operations["getWebhook"];
        put?: never;
        post?: never;
        /** Delete a webhook */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        /** Update a webhook */
        patch: operations["updateWebhook"];
        trace?: never;
    };
    "/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-organization session oversight (super_admin) */
        get: operations["adminListSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error envelope used across the API (§11). */
        Error: {
            error: {
                /** @enum {string} */
                code: "rate_limited" | "not_found" | "unauthorized" | "forbidden" | "validation_error" | "conflict" | "not_implemented" | "internal";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        PageMeta: {
            /** @description Pass back as ?cursor to fetch the next page; null/absent at the end. */
            nextCursor?: string | null;
        };
        CreateSessionRequest: {
            label?: string;
            /** @description Start the session immediately. */
            start?: boolean;
            autoRead?: boolean;
            presenceTyping?: boolean;
        };
        /** @description An attached WhatsApp number (mirrors the wa_sessions table). Owned by an organization (`organizationId`); `gatewayId` names which gateway holds this session's keystore. Per §13 the response also carries the owning gateway's `label`/`status`/`baseUrl` from the `gateways` registry (the optional `gateway` object) so the dashboard can show where each session lives once there is more than one gateway. */
        WASession: {
            /** @description App session id (ULID). */
            id: string;
            /** @description Owning better-auth organization id. */
            organizationId: string;
            /** @description better-auth user that created the session (audit). */
            createdByUserId?: string;
            /** @description Gateway holding this session's keystore (= GATEWAY_ID). */
            gatewayId: string;
            /** @description The owning gateway's registry row (label/status/baseUrl), per §13. */
            gateway?: components["schemas"]["Gateway"];
            label?: string;
            /** @enum {string} */
            status: "starting" | "scan_qr_code" | "working" | "failed" | "stopped" | "logged_out";
            /** @description Phone JID once paired. */
            waJid?: string;
            /** @description Linked-device id. */
            waLid?: string;
            phoneNumber?: string;
            /** @description The WHATSAPP_ADMIN_NUMBER session. */
            isAdminSession: boolean;
            autoRead: boolean;
            presenceTyping: boolean;
            ratePerMin: number;
            ratePerHour: number;
            /** Format: int64 */
            lastConnectedAt?: number;
            /** Format: int64 */
            createdAt: number;
            /** Format: int64 */
            updatedAt: number;
        };
        /** @description A row in the `gateways` registry (§7) — one self-row in v2, more when sharding. Surfaced on session responses so the dashboard knows where a session lives. */
        Gateway: {
            /** @description Gateway id (= GATEWAY_ID). */
            id: string;
            label?: string;
            /**
             * @description Gateway liveness derived from the registry heartbeat.
             * @enum {string}
             */
            status: "online" | "offline";
            /** @description External base URL of this gateway (PUBLIC_URL). */
            baseUrl?: string;
            /** Format: int64 */
            lastSeenAt?: number;
        };
        SessionPage: components["schemas"]["PageMeta"] & {
            data?: components["schemas"]["WASession"][];
        };
        SessionMe: {
            jid?: string;
            lid?: string;
            pushName?: string;
            phoneNumber?: string;
        };
        QRCode: {
            /** @description Raw QR code string to render. */
            code?: string;
        };
        /** @description Discriminated on `type` (§11). */
        SendRequest: {
            /** @enum {string} */
            type: "text" | "poll" | "location" | "contact" | "image" | "video" | "audio" | "document" | "sticker";
            /** @description Recipient JID. */
            to: string;
            text?: string;
            /** @description Quoted message id. */
            replyTo?: string;
            mentions?: string[];
            /** @description Poll name or location label. */
            name?: string;
            options?: string[];
            selectableCount?: number;
            latitude?: number;
            longitude?: number;
            contact?: components["schemas"]["ContactCard"];
        };
        ContactCard: {
            name?: string;
            phone?: string;
            vcard?: string;
        };
        SendResult: {
            messageId?: string;
            /** @enum {string} */
            status?: "pending" | "sent" | "delivered" | "read" | "played" | "failed";
            /** Format: int64 */
            timestamp?: number;
        };
        Message: {
            id?: string;
            chatJid?: string;
            senderJid?: string;
            /** @enum {string} */
            direction?: "in" | "out";
            type?: string;
            body?: string;
            /** @enum {string} */
            status?: "pending" | "sent" | "delivered" | "read" | "played" | "failed";
            /** Format: int64 */
            timestamp?: number;
        };
        MessagePage: components["schemas"]["PageMeta"] & {
            data?: components["schemas"]["Message"][];
        };
        Chat: {
            jid?: string;
            /** @enum {string} */
            type?: "dm" | "group" | "newsletter" | "broadcast" | "status";
            name?: string;
            unreadCount?: number;
            archived?: boolean;
            pinned?: boolean;
            /** Format: int64 */
            mutedUntil?: number;
            /** Format: int64 */
            lastMessageAt?: number;
        };
        ChatPage: components["schemas"]["PageMeta"] & {
            data?: components["schemas"]["Chat"][];
        };
        UpdateChatRequest: {
            archived?: boolean;
            pinned?: boolean;
            /** Format: int64 */
            mutedUntil?: number;
            unmute?: boolean;
        };
        Contact: {
            lid?: string;
            phoneNumber?: string;
            name?: string;
            pushName?: string;
            /** @enum {string} */
            source?: "dm" | "group";
        };
        ContactPage: components["schemas"]["PageMeta"] & {
            data?: components["schemas"]["Contact"][];
        };
        ContactDetail: {
            identity?: components["schemas"]["Contact"];
            /** @description Whether a DM chat exists. */
            dm?: boolean;
            groups?: {
                jid?: string;
                name?: string;
                nickname?: string;
                /** @enum {string} */
                role?: "member" | "admin" | "superadmin";
                /** Format: int64 */
                lastSeen?: number;
            }[];
        };
        OnWhatsApp: {
            query?: string;
            jid?: string;
            isIn?: boolean;
            verifiedName?: string;
        };
        ProfilePicture: {
            url?: string;
            id?: string;
            type?: string;
        };
        GroupInfo: {
            jid?: string;
            subject?: string;
            description?: string;
            owner?: string;
            announce?: boolean;
            locked?: boolean;
            participants?: components["schemas"]["GroupMember"][];
        };
        GroupMember: {
            jid?: string;
            nickname?: string;
            /** @enum {string} */
            role?: "member" | "admin" | "superadmin";
        };
        GroupSettings: {
            subject?: string;
            description?: string;
            announce?: boolean;
            locked?: boolean;
        };
        GroupPage: components["schemas"]["PageMeta"] & {
            data?: components["schemas"]["GroupInfo"][];
        };
        RetryPolicy: {
            /** @example exponential */
            policy?: string;
            delaySeconds?: number;
            attempts?: number;
        };
        WebhookRequest: {
            /** @description Null = all of the organization's sessions. */
            sessionId?: string;
            url?: string;
            events?: string[];
            secret?: string;
            customHeaders?: {
                [key: string]: string;
            };
            retryPolicy?: components["schemas"]["RetryPolicy"];
            active?: boolean;
        };
        Webhook: {
            id?: string;
            organizationId?: string;
            sessionId?: string;
            url?: string;
            events?: string[];
            customHeaders?: {
                [key: string]: string;
            };
            retryPolicy?: components["schemas"]["RetryPolicy"];
            active?: boolean;
            /** Format: int64 */
            createdAt?: number;
            /** Format: int64 */
            updatedAt?: number;
        };
        WebhookPage: components["schemas"]["PageMeta"] & {
            data?: components["schemas"]["Webhook"][];
        };
        /** @description The §9 event envelope, one per NDJSON line. */
        Event: {
            /** @example v1 */
            schema: string;
            /** @example evt_01J9... */
            id: string;
            /** @description Event type, e.g. message, session.status, group.update. */
            event: string;
            session: string;
            /** @description Owning organization id. */
            organization: string;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            timestamp: number;
            payload: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Error envelope (§11). */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The send result. */
        SendResultOK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SendResult"];
            };
        };
    };
    parameters: {
        /** @description The WhatsApp session id (sess_…). */
        Session: string;
        ID: string;
        /** @description WhatsApp message id. */
        MessageID: string;
        /** @description Chat JID. */
        ChatID: string;
        /** @description Group JID. */
        GroupID: string;
        /** @description A WhatsApp JID. */
        JID: string;
        /** @description Max items to return. */
        Limit: number;
        /** @description Opaque pagination cursor from a previous response's nextCursor. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["Error"];
        };
    };
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI spec. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WASession"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WASession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WASession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    stopSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session stopped. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WASession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    restartSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session restarted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WASession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    logoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session logged out. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WASession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    sessionMe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMe"];
                };
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    sessionQR: {
        parameters: {
            query?: {
                /** @description Return a QR image instead of the raw code string. */
                format?: "image";
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QR code (raw code, or PNG when ?format=image). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRCode"];
                    "image/png": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    sessionPairingCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 628123456789 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description Pairing code. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ABCD-1234 */
                        code?: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    sendMessage: {
        parameters: {
            query?: {
                /** @description Enqueue and return immediately instead of sending inline. */
                async?: boolean;
            };
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendRequest"];
            };
        };
        responses: {
            /** @description Sent (or accepted when async). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendResult"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    revokeMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SendResultOK"];
            404: components["responses"]["Error"];
        };
    };
    editMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            200: components["responses"]["SendResultOK"];
            404: components["responses"]["Error"];
        };
    };
    addReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 👍 */
                    emoji: string;
                };
            };
        };
        responses: {
            200: components["responses"]["SendResultOK"];
            404: components["responses"]["Error"];
        };
    };
    removeReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SendResultOK"];
            404: components["responses"]["Error"];
        };
    };
    forwardMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Recipient JID */
                    to: string;
                };
            };
        };
        responses: {
            200: components["responses"]["SendResultOK"];
            404: components["responses"]["Error"];
        };
    };
    voteMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description WhatsApp message id. */
                mid: components["parameters"]["MessageID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    options: string[];
                };
            };
        };
        responses: {
            200: components["responses"]["SendResultOK"];
            404: components["responses"]["Error"];
        };
    };
    listChats: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of chats. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatPage"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The chat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    updateChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChatRequest"];
            };
        };
        responses: {
            /** @description Updated chat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listChatMessages: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    readChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    messageIds?: string[];
                };
            };
        };
        responses: {
            /** @description Marked read. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    chatPresence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Chat JID. */
                cid: components["parameters"]["ChatID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    state: "composing" | "paused" | "recording";
                };
            };
        };
        responses: {
            /** @description Presence sent. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    listContacts: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
                source?: "dm" | "group";
                /** @description Filter to members of this group JID. */
                group?: string;
                /** @description Free-text search over name/number. */
                q?: string;
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of contacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactPage"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    checkContact: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description On-WhatsApp result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnWhatsApp"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    getContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contact detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    contactPicture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile picture URL/metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePicture"];
                };
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    contactAbout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description About text. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        about?: string;
                    };
                };
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    blockContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blocked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    unblockContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unblocked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupPage"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    subject: string;
                    participants: string[];
                };
            };
        };
        responses: {
            /** @description Created group. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"];
                };
            };
            400: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    joinGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    invite: string;
                };
            };
        };
        responses: {
            /** @description Joined. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"];
                };
            };
            501: components["responses"]["Error"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupSettings"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    leaveGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Left. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    listGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"][];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    addGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    participants: string[];
                };
            };
        };
        responses: {
            /** @description Added. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    approveGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    promoteGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Promoted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    demoteGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demoted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    getGroupInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite link. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invite?: string;
                    };
                };
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    revokeGroupInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description Group JID. */
                gid: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New invite link. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invite?: string;
                    };
                };
            };
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    followChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    unfollowChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    muteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    listChannelMessages: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
                /** @description A WhatsApp JID. */
                jid: components["parameters"]["JID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    postStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example text
                     * @enum {string}
                     */
                    type: "text" | "image";
                    text?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["SendResultOK"];
            400: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    setPresence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The WhatsApp session id (sess_…). */
                session: components["parameters"]["Session"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    state: "online" | "offline";
                };
            };
        };
        responses: {
            /** @description Presence set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            501: components["responses"]["Error"];
        };
    };
    events: {
        parameters: {
            query?: {
                /** @description Comma-separated event type filter. */
                types?: string;
                /** @description Restrict to one session id. */
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An NDJSON stream; one Event JSON object per line. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of webhooks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookPage"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookRequest"];
            };
        };
        responses: {
            /** @description The created webhook. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The webhook. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookRequest"];
            };
        };
        responses: {
            /** @description The updated webhook. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminListSessions: {
        parameters: {
            query?: {
                /** @description Max items to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque pagination cursor from a previous response's nextCursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sessions across all organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
}
