import { useState } from "react";
import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { RefreshCwIcon, Trash2Icon } from "lucide-react";
import { useAdminGateway, useAdminGatewayAction, useAdminGatewayEnrollment, useDeleteAdminGateway } from "~/lib/api/hooks/admin";
import { isApiError } from "~/lib/api/envelope";
import { Button } from "~/components/ui/button";
import { Badge } from "~/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "~/components/ui/dialog";
import { GatewayEnrollmentResult } from "./-gateway-enrollment";
import { journalPressure, keystoreBytes, keystorePresence, reconciliationSubject, revisionGap } from "./-gateway-reconciliation";

export const Route = createFileRoute("/_app/admin/gateways/$gatewayId")({ component: GatewayDetail });

function GatewayDetail() {
  const { gatewayId } = Route.useParams(); const navigate = useNavigate();
  const query = useAdminGateway(gatewayId); const action = useAdminGatewayAction(); const reenroll = useAdminGatewayEnrollment("reenroll"); const replace = useAdminGatewayEnrollment("replace-enrollment-token"); const del = useDeleteAdminGateway();
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [result, setResult] = useState<Parameters<typeof GatewayEnrollmentResult>[0]["result"] | null>(null);
  if (result) return <div className="space-y-4"><GatewayEnrollmentResult result={result} onDismiss={() => setResult(null)} /><Button asChild variant="outline"><Link to="/admin/gateways/$gatewayId" params={{ gatewayId }}>Back to gateway</Link></Button></div>;
  if (query.isLoading) return <p className="text-sm text-muted-foreground">Loading gateway…</p>;
  if (query.isError || !query.data) return <div className="space-y-3"><p className="text-sm text-destructive">{query.isError && isApiError(query.error) ? query.error.message : "Gateway not found"}</p><Button asChild variant="outline"><Link to="/admin/gateways">Back to gateways</Link></Button></div>;
  const { gateway, assignedSessions, activeCertificate, audit, reconciliationResults } = query.data;
  const call = (name: "disable" | "drain" | "reenable" | "resume") => action.mutate({ gatewayId, action: name });
  const error = action.error ?? reenroll.error ?? replace.error ?? del.error;
  const busy = action.isPending || reenroll.isPending || replace.isPending || del.isPending;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-2"><div><Link to="/admin/gateways" className="text-sm text-muted-foreground hover:underline">← Gateways</Link><h1 className="text-xl font-semibold">{gateway.label || gateway.id}</h1><p className="font-mono text-xs text-muted-foreground">{gateway.id}</p></div><div className="flex gap-2"><Badge variant="secondary">{gateway.status}</Badge><Button variant="outline" size="sm" onClick={() => void query.refetch()}><RefreshCwIcon className="mr-2 size-4" />Refresh</Button></div></div>
    <Card><CardHeader><CardTitle className="text-base">Observed state</CardTitle><CardDescription>Explicit refresh keeps operational state current without retaining enrollment data.</CardDescription></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><Fact label="Desired lifecycle" value={gateway.desiredLifecycle} /><Fact label="Reconciliation" value={gateway.reconciliationStatus} /><Fact label="Sessions" value={`${gateway.sessionCount} live / ${query.data.assignedSessionCount} assigned`} /><Fact label="Last heartbeat" value={time(gateway.lastSeenAt)} /><Fact label="Connected" value={time(gateway.connectedAt)} /><Fact label="Software" value={gateway.softwareVersion || "—"} /><Fact label="Revisions" value={revisionGap(gateway.appliedRevision, gateway.desiredRevision)} /><Fact label="Connection" value={`${gateway.connectionMode} #${gateway.connectionEpoch}`} /><Fact label="Certificate expiry" value={activeCertificate ? time(activeCertificate.notAfter) : "—"} /><Fact label="Keystore presence" value={keystorePresence(gateway)} /><Fact label="Keystore integrity" value={gateway.keystoreIntegrity || "Not reported"} /><Fact label="Keystore bytes" value={keystoreBytes(gateway)} /><Fact label="Keystore checked" value={time(gateway.keystoreCheckedAt)} /><Fact label="Event journal" value={journalPressure(gateway)} /><Fact label="Capabilities" value={gateway.capabilities ? JSON.stringify(gateway.capabilities) : "—"} /></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Lifecycle</CardTitle><CardDescription>Drain prevents new placement. Disable immediately rejects the gateway connection.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => call("drain")}>Drain</Button><Button variant="outline" disabled={busy} onClick={() => call("resume")}>Resume</Button><Button variant="outline" disabled={busy} onClick={() => call("disable")}>Disable</Button><Button variant="outline" disabled={busy} onClick={() => call("reenable")}>Re-enable</Button><Button variant="outline" disabled={busy} onClick={() => replace.mutate(gatewayId, { onSuccess: setResult })}>Replace enrollment token</Button><Button variant="outline" disabled={busy} onClick={() => reenroll.mutate(gatewayId, { onSuccess: setResult })}>Re-enroll</Button><Button variant="destructive" disabled={busy} onClick={() => setDeleteOpen(true)}><Trash2Icon className="mr-2 size-4" />Delete</Button></CardContent></Card>
    {error && <p className="text-sm text-destructive">{isApiError(error) ? error.message : "Gateway action failed"}</p>}
    <Card><CardHeader><CardTitle className="text-base">Assigned sessions</CardTitle></CardHeader><CardContent>{assignedSessions?.length ? <ul className="space-y-2">{assignedSessions.map((session) => <li key={session.id} className="rounded border p-2 text-sm">{session.label || session.id}<span className="ml-2 font-mono text-xs text-muted-foreground">{session.id}</span></li>)}</ul> : <p className="text-sm text-muted-foreground">No assigned sessions.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Reconciliation results</CardTitle><CardDescription>Current local device and assigned-session outcomes.</CardDescription></CardHeader><CardContent>{reconciliationResults?.length ? <ul className="space-y-2">{reconciliationResults.map((entry) => <li key={`${entry.deviceJid}:${entry.assignmentEpoch}`} className="rounded border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{reconciliationSubject(entry)}</span><Badge variant="secondary">{entry.status}</Badge></div><p className="mt-1 font-mono text-xs text-muted-foreground">{entry.deviceJid}</p><p className="mt-1 text-xs text-muted-foreground">Desired revision {entry.desiredRevision} · assignment epoch {entry.assignmentEpoch} · updated {time(entry.updatedAt)}</p></li>)}</ul> : <p className="text-sm text-muted-foreground">No reconciliation results reported.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Audit</CardTitle></CardHeader><CardContent>{audit?.length ? <ul className="space-y-2">{audit.map((entry) => <li key={entry.id} className="text-sm"><span className="font-medium">{entry.action}</span> · {entry.outcome} · {time(entry.createdAt)}</li>)}</ul> : <p className="text-sm text-muted-foreground">No audit events.</p>}</CardContent></Card>
    <Dialog open={deleteOpen} onOpenChange={setDeleteOpen}><DialogContent><DialogHeader><DialogTitle>Delete this gateway?</DialogTitle><DialogDescription>Deletion is allowed only after the gateway is drained or disabled, has no assigned sessions, no active enrollment token, and no usable certificate. Confirming acknowledges that its sessions and devices have been reviewed. This action cannot be undone.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="outline">Cancel</Button></DialogClose><Button variant="destructive" disabled={del.isPending} onClick={() => del.mutate(gatewayId, { onSuccess: () => void navigate({ to: "/admin/gateways" }) })}>{del.isPending ? "Deleting…" : "Acknowledge and delete"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="break-all">{value}</p></div>; }
function time(value?: number) { return value ? new Date(value).toLocaleString() : "—"; }
